/*Primary keys*/
ALTER TABLE Productos ADD CONSTRAINT Producto_PK PRIMARY KEY (IDProducto);
ALTER TABLE DetallesProductos ADD CONSTRAINT DestalleProducto_PK PRIMARY KEY (IDDetalleProducto);

ALTER TABLE Socios ADD CONSTRAINT Socios_PK PRIMARY KEY (IDSocio);
ALTER TABLE Proveedores ADD CONSTRAINT Proveedores_PK PRIMARY KEY (IDProveedor);
ALTER TABLE EstablecimientosFisicos ADD CONSTRAINT Fisico_PK PRIMARY KEY (IDFisico);
ALTER TABLE DireccionesEstablecimientos ADD CONSTRAINT DireccionesEstablecimientos_PK PRIMARY KEY (IDDireccion);
ALTER TABLE Blogs ADD CONSTRAINT Blog_PK PRIMARY KEY (IDBlog);
ALTER TABLE Reviews ADD CONSTRAINT Review_PK PRIMARY KEY (IDReview);
ALTER TABLE PaginasDigitales ADD CONSTRAINT Paginas_PK PRIMARY KEY (IDPaginas);

ALTER TABLE Links ADD CONSTRAINT Link_PK PRIMARY KEY (IDLink);
ALTER TABLE Cobros ADD CONSTRAINT Cobros_PK PRIMARY KEY (IDCobro);
ALTER TABLE Pagos ADD CONSTRAINT Pagos_PK PRIMARY KEY (IDPago);

ALTER TABLE Usuarios ADD CONSTRAINT Usuarios_PK PRIMARY KEY (IDUsuario);
ALTER TABLE DireccionesUsuarios ADD CONSTRAINT DireccionesUsuarios_PK PRIMARY KEY (IDDireccion);
ALTER TABLE Clicks ADD CONSTRAINT Clicks_PK PRIMARY KEY (IDClick);

ALTER TABLE Auspiciados ADD CONSTRAINT Auspiciado_PK PRIMARY KEY (IDAuspiciado);
ALTER TABLE Cupos ADD CONSTRAINT Cupos_PK PRIMARY KEY (Nombre);
