INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('1', '1', 'Colombia', 'Bogota', 'Departamento', 'Grasskamp');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('2', '2', 'Colombia', 'Bogota', 'Departamento', 'Autumn Leaf');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('3', '3', 'Colombia', 'Bogota', 'Departamento', 'Browning');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('4', '4', 'Colombia', 'Medellin', 'Departamento', 'Donald');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('5', '5', 'Colombia', 'Bogota', 'Departamento', 'Del Mar');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('6', '6', 'Colombia', 'Cali', 'Departamento', 'Goodland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('7', '7', 'Colombia', 'Cali', 'Departamento', 'Butternut');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('8', '8', 'Colombia', 'Medellin', 'Departamento', 'Eggendart');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('9', '9', 'Colombia', 'Cali', 'Departamento', 'Vahlen');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('10', '10', 'Colombia', 'Cali', 'Departamento', 'John Wall');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('11', '11', 'Colombia', 'Cartegena', 'Departamento', 'Hollow Ridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('12', '12', 'Colombia', 'Bogota', 'Departamento', 'Green Ridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('13', '13', 'Colombia', 'Cartegena', 'Departamento', 'Tomscot');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('14', '14', 'Colombia', 'Medellin', 'Departamento', 'Vernon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('15', '15', 'Colombia', 'Cali', 'Departamento', 'Eggendart');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('16', '16', 'Colombia', 'Cali', 'Departamento', '6th');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('17', '17', 'Colombia', 'Cartegena', 'Departamento', 'Lakeland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('18', '18', 'Colombia', 'Medellin', 'Departamento', 'Mitchell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('19', '19', 'Colombia', 'Medellin', 'Departamento', 'Eggendart');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('20', '20', 'Colombia', 'Medellin', 'Departamento', 'Monument');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('21', '21', 'Colombia', 'Medellin', 'Departamento', 'Burrows');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('22', '22', 'Colombia', 'Cali', 'Departamento', 'Coleman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('23', '23', 'Colombia', 'Cartegena', 'Departamento', 'Lawn');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('24', '24', 'Colombia', 'Cali', 'Departamento', 'Cottonwood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('25', '25', 'Colombia', 'Medellin', 'Departamento', 'Tennessee');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('26', '26', 'Colombia', 'Cali', 'Departamento', 'Spaight');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('27', '27', 'Colombia', 'Medellin', 'Departamento', 'Cherokee');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('28', '28', 'Colombia', 'Medellin', 'Departamento', 'Banding');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('29', '29', 'Colombia', 'Medellin', 'Departamento', 'Sachtjen');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('30', '30', 'Colombia', 'Cartegena', 'Departamento', 'Summerview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('31', '31', 'Colombia', 'Bogota', 'Departamento', 'Dottie');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('32', '32', 'Colombia', 'Cartegena', 'Departamento', 'Reindahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('33', '33', 'Colombia', 'Cali', 'Departamento', 'Russell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('34', '34', 'Colombia', 'Cali', 'Departamento', 'Anhalt');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('35', '35', 'Colombia', 'Bogota', 'Departamento', 'School');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('36', '36', 'Colombia', 'Cali', 'Departamento', 'Florence');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('37', '37', 'Colombia', 'Cartegena', 'Departamento', 'Memorial');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('38', '38', 'Colombia', 'Medellin', 'Departamento', 'Truax');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('39', '39', 'Colombia', 'Medellin', 'Departamento', 'Mayer');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('40', '40', 'Colombia', 'Cali', 'Departamento', 'Garrison');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('41', '41', 'Colombia', 'Medellin', 'Departamento', 'Lerdahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('42', '42', 'Colombia', 'Cartegena', 'Departamento', 'Clarendon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('43', '43', 'Colombia', 'Cartegena', 'Departamento', 'Main');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('44', '44', 'Colombia', 'Medellin', 'Departamento', 'Northview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('45', '45', 'Colombia', 'Cali', 'Departamento', 'Mesta');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('46', '46', 'Colombia', 'Bogota', 'Departamento', 'Kim');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('47', '47', 'Colombia', 'Cali', 'Departamento', 'Lunder');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('48', '48', 'Colombia', 'Cartegena', 'Departamento', 'Vera');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('49', '49', 'Colombia', 'Bogota', 'Departamento', 'Spaight');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('50', '50', 'Colombia', 'Bogota', 'Departamento', 'Holy Cross');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('51', '51', 'Colombia', 'Medellin', 'Departamento', 'Lawn');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('52', '52', 'Colombia', 'Bogota', 'Departamento', 'Victoria');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('53', '53', 'Colombia', 'Cartegena', 'Departamento', 'Corscot');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('54', '54', 'Colombia', 'Cartegena', 'Departamento', 'Emmet');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('55', '55', 'Colombia', 'Cali', 'Departamento', 'Calypso');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('56', '56', 'Colombia', 'Cartegena', 'Departamento', 'Talisman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('57', '57', 'Colombia', 'Bogota', 'Departamento', 'Daystar');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('58', '58', 'Colombia', 'Cali', 'Departamento', 'Lunder');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('59', '59', 'Colombia', 'Cartegena', 'Departamento', 'Clarendon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('60', '60', 'Colombia', 'Cali', 'Departamento', 'Mitchell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('61', '61', 'Colombia', 'Medellin', 'Departamento', 'Crescent Oaks');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('62', '62', 'Colombia', 'Bogota', 'Departamento', 'Dapin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('63', '63', 'Colombia', 'Bogota', 'Departamento', 'Summerview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('64', '64', 'Colombia', 'Cali', 'Departamento', 'Graceland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('65', '65', 'Colombia', 'Bogota', 'Departamento', 'Blue Bill Park');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('66', '66', 'Colombia', 'Medellin', 'Departamento', 'Crescent Oaks');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('67', '67', 'Colombia', 'Cali', 'Departamento', 'Thompson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('68', '68', 'Colombia', 'Bogota', 'Departamento', 'Marquette');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('69', '69', 'Colombia', 'Cartegena', 'Departamento', 'Sutteridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('70', '70', 'Colombia', 'Cartegena', 'Departamento', 'Bowman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('71', '71', 'Colombia', 'Bogota', 'Departamento', 'Tony');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('72', '72', 'Colombia', 'Cali', 'Departamento', 'Waywood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('73', '73', 'Colombia', 'Cartegena', 'Departamento', 'Forest');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('74', '74', 'Colombia', 'Cartegena', 'Departamento', 'Steensland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('75', '75', 'Colombia', 'Cali', 'Departamento', 'Mccormick');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('76', '76', 'Colombia', 'Medellin', 'Departamento', 'Rigney');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('77', '77', 'Colombia', 'Cartegena', 'Departamento', 'Brown');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('78', '78', 'Colombia', 'Bogota', 'Departamento', 'Transport');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('79', '79', 'Colombia', 'Medellin', 'Departamento', 'Sauthoff');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('80', '80', 'Colombia', 'Medellin', 'Departamento', 'Crowley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('81', '81', 'Colombia', 'Cartegena', 'Departamento', 'Pleasure');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('82', '82', 'Colombia', 'Cartegena', 'Departamento', 'Becker');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('83', '83', 'Colombia', 'Bogota', 'Departamento', 'Eastlawn');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('84', '84', 'Colombia', 'Bogota', 'Departamento', 'Montana');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('85', '85', 'Colombia', 'Medellin', 'Departamento', 'Express');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('86', '86', 'Colombia', 'Cali', 'Departamento', 'Arkansas');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('87', '87', 'Colombia', 'Cali', 'Departamento', 'Mosinee');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('88', '88', 'Colombia', 'Cali', 'Departamento', 'Laurel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('89', '89', 'Colombia', 'Cartegena', 'Departamento', 'Carioca');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('90', '90', 'Colombia', 'Cartegena', 'Departamento', 'Twin Pines');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('91', '91', 'Colombia', 'Bogota', 'Departamento', 'Thierer');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('92', '92', 'Colombia', 'Cali', 'Departamento', 'Anniversary');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('93', '93', 'Colombia', 'Medellin', 'Departamento', 'Kennedy');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('94', '94', 'Colombia', 'Bogota', 'Departamento', 'Mandrake');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('95', '95', 'Colombia', 'Cartegena', 'Departamento', 'Dapin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('96', '96', 'Colombia', 'Medellin', 'Departamento', 'Autumn Leaf');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('97', '97', 'Colombia', 'Cartegena', 'Departamento', 'Mifflin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('98', '98', 'Colombia', 'Cali', 'Departamento', 'Sauthoff');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('99', '99', 'Colombia', 'Cali', 'Departamento', 'Roth');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('100', '100', 'Colombia', 'Cartegena', 'Departamento', 'Ronald Regan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('101', '101', 'Colombia', 'Cali', 'Departamento', 'Fisk');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('102', '102', 'Colombia', 'Cartegena', 'Departamento', 'Mallory');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('103', '103', 'Colombia', 'Cartegena', 'Departamento', 'Scott');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('104', '104', 'Colombia', 'Medellin', 'Departamento', 'Texas');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('105', '105', 'Colombia', 'Cartegena', 'Departamento', 'Maple Wood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('106', '106', 'Colombia', 'Bogota', 'Departamento', 'Russell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('107', '107', 'Colombia', 'Cartegena', 'Departamento', 'Buena Vista');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('108', '108', 'Colombia', 'Bogota', 'Departamento', 'Loomis');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('109', '109', 'Colombia', 'Cartegena', 'Departamento', 'Drewry');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('110', '110', 'Colombia', 'Cartegena', 'Departamento', 'Dapin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('111', '111', 'Colombia', 'Bogota', 'Departamento', 'Colorado');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('112', '112', 'Colombia', 'Cali', 'Departamento', 'Oriole');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('113', '113', 'Colombia', 'Cali', 'Departamento', 'Daystar');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('114', '114', 'Colombia', 'Medellin', 'Departamento', 'Dunning');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('115', '115', 'Colombia', 'Cali', 'Departamento', 'Warner');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('116', '116', 'Colombia', 'Cali', 'Departamento', 'Daystar');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('117', '117', 'Colombia', 'Medellin', 'Departamento', 'Transport');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('118', '118', 'Colombia', 'Bogota', 'Departamento', 'Mandrake');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('119', '119', 'Colombia', 'Medellin', 'Departamento', 'Rutledge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('120', '120', 'Colombia', 'Cali', 'Departamento', 'Loeprich');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('121', '121', 'Colombia', 'Cali', 'Departamento', 'Sachs');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('122', '122', 'Colombia', 'Cali', 'Departamento', 'Waxwing');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('123', '123', 'Colombia', 'Cali', 'Departamento', 'Stone Corner');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('124', '124', 'Colombia', 'Medellin', 'Departamento', 'Harper');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('125', '125', 'Colombia', 'Bogota', 'Departamento', 'Starling');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('126', '126', 'Colombia', 'Medellin', 'Departamento', 'Memorial');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('127', '127', 'Colombia', 'Bogota', 'Departamento', 'Luster');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('128', '128', 'Colombia', 'Medellin', 'Departamento', 'Golden Leaf');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('129', '129', 'Colombia', 'Medellin', 'Departamento', 'Dennis');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('130', '130', 'Colombia', 'Medellin', 'Departamento', 'Haas');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('131', '131', 'Colombia', 'Cali', 'Departamento', 'Merrick');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('132', '132', 'Colombia', 'Cartegena', 'Departamento', 'Old Shore');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('133', '133', 'Colombia', 'Cali', 'Departamento', 'Londonderry');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('134', '134', 'Colombia', 'Bogota', 'Departamento', 'Prairie Rose');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('135', '135', 'Colombia', 'Cartegena', 'Departamento', 'Hansons');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('136', '136', 'Colombia', 'Cali', 'Departamento', 'Derek');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('137', '137', 'Colombia', 'Bogota', 'Departamento', 'Thackeray');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('138', '138', 'Colombia', 'Bogota', 'Departamento', 'David');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('139', '139', 'Colombia', 'Cali', 'Departamento', 'Dottie');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('140', '140', 'Colombia', 'Bogota', 'Departamento', 'Sullivan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('141', '141', 'Colombia', 'Cali', 'Departamento', 'Clove');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('142', '142', 'Colombia', 'Cartegena', 'Departamento', 'International');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('143', '143', 'Colombia', 'Cali', 'Departamento', 'Nevada');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('144', '144', 'Colombia', 'Medellin', 'Departamento', 'Buell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('145', '145', 'Colombia', 'Cali', 'Departamento', 'Eastlawn');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('146', '146', 'Colombia', 'Cartegena', 'Departamento', 'Elka');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('147', '147', 'Colombia', 'Cali', 'Departamento', 'Debs');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('148', '148', 'Colombia', 'Medellin', 'Departamento', '2nd');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('149', '149', 'Colombia', 'Bogota', 'Departamento', 'Ridgeview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('150', '150', 'Colombia', 'Bogota', 'Departamento', 'Center');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('151', '151', 'Colombia', 'Bogota', 'Departamento', 'Fisk');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('152', '152', 'Colombia', 'Cartegena', 'Departamento', 'Green Ridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('153', '153', 'Colombia', 'Bogota', 'Departamento', 'Cardinal');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('154', '154', 'Colombia', 'Medellin', 'Departamento', 'Arkansas');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('155', '155', 'Colombia', 'Cali', 'Departamento', 'Sloan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('156', '156', 'Colombia', 'Cartegena', 'Departamento', 'Elmside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('157', '157', 'Colombia', 'Cartegena', 'Departamento', 'Aberg');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('158', '158', 'Colombia', 'Medellin', 'Departamento', 'Dennis');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('159', '159', 'Colombia', 'Bogota', 'Departamento', 'Coolidge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('160', '160', 'Colombia', 'Bogota', 'Departamento', 'Arrowood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('161', '161', 'Colombia', 'Bogota', 'Departamento', 'Manufacturers');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('162', '162', 'Colombia', 'Medellin', 'Departamento', 'Stang');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('163', '163', 'Colombia', 'Bogota', 'Departamento', 'Ridgeway');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('164', '164', 'Colombia', 'Bogota', 'Departamento', 'Debs');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('165', '165', 'Colombia', 'Cartegena', 'Departamento', 'Moulton');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('166', '166', 'Colombia', 'Cartegena', 'Departamento', 'Becker');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('167', '167', 'Colombia', 'Bogota', 'Departamento', 'Morning');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('168', '168', 'Colombia', 'Cartegena', 'Departamento', 'Little Fleur');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('169', '169', 'Colombia', 'Medellin', 'Departamento', 'Hintze');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('170', '170', 'Colombia', 'Cali', 'Departamento', 'Northport');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('171', '171', 'Colombia', 'Bogota', 'Departamento', 'Annamark');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('172', '172', 'Colombia', 'Bogota', 'Departamento', 'Barby');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('173', '173', 'Colombia', 'Cali', 'Departamento', 'Kennedy');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('174', '174', 'Colombia', 'Cartegena', 'Departamento', 'Vermont');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('175', '175', 'Colombia', 'Medellin', 'Departamento', 'Lindbergh');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('176', '176', 'Colombia', 'Medellin', 'Departamento', 'Michigan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('177', '177', 'Colombia', 'Cali', 'Departamento', 'Holmberg');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('178', '178', 'Colombia', 'Cali', 'Departamento', 'Burrows');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('179', '179', 'Colombia', 'Cartegena', 'Departamento', 'Pankratz');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('180', '180', 'Colombia', 'Medellin', 'Departamento', 'Mcguire');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('181', '181', 'Colombia', 'Cali', 'Departamento', 'Towne');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('182', '182', 'Colombia', 'Cali', 'Departamento', 'Sycamore');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('183', '183', 'Colombia', 'Medellin', 'Departamento', 'Golden Leaf');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('184', '184', 'Colombia', 'Cartegena', 'Departamento', 'Mccormick');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('185', '185', 'Colombia', 'Bogota', 'Departamento', 'Laurel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('186', '186', 'Colombia', 'Cali', 'Departamento', 'Anderson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('187', '187', 'Colombia', 'Bogota', 'Departamento', 'Nova');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('188', '188', 'Colombia', 'Bogota', 'Departamento', 'Nova');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('189', '189', 'Colombia', 'Medellin', 'Departamento', 'Gateway');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('190', '190', 'Colombia', 'Medellin', 'Departamento', 'Bunker Hill');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('191', '191', 'Colombia', 'Cartegena', 'Departamento', 'Pennsylvania');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('192', '192', 'Colombia', 'Bogota', 'Departamento', 'Merchant');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('193', '193', 'Colombia', 'Cartegena', 'Departamento', 'Sullivan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('194', '194', 'Colombia', 'Cartegena', 'Departamento', 'Helena');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('195', '195', 'Colombia', 'Cali', 'Departamento', 'Portage');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('196', '196', 'Colombia', 'Medellin', 'Departamento', 'Comanche');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('197', '197', 'Colombia', 'Cartegena', 'Departamento', '1st');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('198', '198', 'Colombia', 'Medellin', 'Departamento', 'Di Loreto');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('199', '199', 'Colombia', 'Bogota', 'Departamento', 'New Castle');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('200', '200', 'Colombia', 'Bogota', 'Departamento', 'Westerfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('201', '201', 'Colombia', 'Medellin', 'Departamento', 'Main');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('202', '202', 'Colombia', 'Medellin', 'Departamento', 'Pearson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('203', '203', 'Colombia', 'Medellin', 'Departamento', 'Grasskamp');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('204', '204', 'Colombia', 'Bogota', 'Departamento', 'Tomscot');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('205', '205', 'Colombia', 'Cartegena', 'Departamento', 'Lerdahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('206', '206', 'Colombia', 'Bogota', 'Departamento', 'Annamark');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('207', '207', 'Colombia', 'Bogota', 'Departamento', 'Brown');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('208', '208', 'Colombia', 'Medellin', 'Departamento', 'Elka');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('209', '209', 'Colombia', 'Cartegena', 'Departamento', 'Monica');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('210', '210', 'Colombia', 'Cali', 'Departamento', 'Macpherson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('211', '211', 'Colombia', 'Bogota', 'Departamento', 'Rockefeller');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('212', '212', 'Colombia', 'Bogota', 'Departamento', 'Superior');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('213', '213', 'Colombia', 'Cali', 'Departamento', 'Butternut');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('214', '214', 'Colombia', 'Bogota', 'Departamento', 'Russell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('215', '215', 'Colombia', 'Medellin', 'Departamento', 'Hanover');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('216', '216', 'Colombia', 'Cali', 'Departamento', 'Mallard');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('217', '217', 'Colombia', 'Bogota', 'Departamento', 'Lighthouse Bay');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('218', '218', 'Colombia', 'Medellin', 'Departamento', 'Raven');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('219', '219', 'Colombia', 'Cali', 'Departamento', 'Rowland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('220', '220', 'Colombia', 'Cartegena', 'Departamento', 'Delladonna');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('221', '221', 'Colombia', 'Cartegena', 'Departamento', 'Service');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('222', '222', 'Colombia', 'Cali', 'Departamento', 'Burrows');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('223', '223', 'Colombia', 'Cartegena', 'Departamento', 'Kim');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('224', '224', 'Colombia', 'Bogota', 'Departamento', 'Westend');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('225', '225', 'Colombia', 'Bogota', 'Departamento', 'Rowland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('226', '226', 'Colombia', 'Cartegena', 'Departamento', 'Eggendart');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('227', '227', 'Colombia', 'Medellin', 'Departamento', 'Dwight');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('228', '228', 'Colombia', 'Bogota', 'Departamento', 'Bunker Hill');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('229', '229', 'Colombia', 'Bogota', 'Departamento', 'Truax');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('230', '230', 'Colombia', 'Cartegena', 'Departamento', 'Hermina');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('231', '231', 'Colombia', 'Cali', 'Departamento', 'Waywood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('232', '232', 'Colombia', 'Cartegena', 'Departamento', 'Graedel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('233', '233', 'Colombia', 'Bogota', 'Departamento', 'Debs');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('234', '234', 'Colombia', 'Medellin', 'Departamento', 'Scott');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('235', '235', 'Colombia', 'Medellin', 'Departamento', 'Bluejay');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('236', '236', 'Colombia', 'Cali', 'Departamento', 'Village');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('237', '237', 'Colombia', 'Cali', 'Departamento', 'Maywood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('238', '238', 'Colombia', 'Medellin', 'Departamento', 'East');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('239', '239', 'Colombia', 'Cartegena', 'Departamento', 'Lakewood Gardens');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('240', '240', 'Colombia', 'Cartegena', 'Departamento', 'Oxford');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('241', '241', 'Colombia', 'Medellin', 'Departamento', 'Coolidge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('242', '242', 'Colombia', 'Medellin', 'Departamento', 'Forest Dale');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('243', '243', 'Colombia', 'Cali', 'Departamento', 'Melody');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('244', '244', 'Colombia', 'Bogota', 'Departamento', 'Cordelia');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('245', '245', 'Colombia', 'Medellin', 'Departamento', 'Anderson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('246', '246', 'Colombia', 'Cartegena', 'Departamento', 'Sloan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('247', '247', 'Colombia', 'Bogota', 'Departamento', 'Northview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('248', '248', 'Colombia', 'Cali', 'Departamento', 'Walton');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('249', '249', 'Colombia', 'Medellin', 'Departamento', 'Arkansas');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('250', '250', 'Colombia', 'Bogota', 'Departamento', 'Schiller');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('251', '251', 'Colombia', 'Medellin', 'Departamento', 'Dayton');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('252', '252', 'Colombia', 'Cali', 'Departamento', 'Chive');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('253', '253', 'Colombia', 'Cartegena', 'Departamento', 'Parkside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('254', '254', 'Colombia', 'Bogota', 'Departamento', 'Katie');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('255', '255', 'Colombia', 'Medellin', 'Departamento', 'Bluejay');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('256', '256', 'Colombia', 'Medellin', 'Departamento', 'Macpherson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('257', '257', 'Colombia', 'Medellin', 'Departamento', 'Rockefeller');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('258', '258', 'Colombia', 'Bogota', 'Departamento', 'Macpherson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('259', '259', 'Colombia', 'Cartegena', 'Departamento', 'Twin Pines');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('260', '260', 'Colombia', 'Cartegena', 'Departamento', 'Oak Valley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('261', '261', 'Colombia', 'Bogota', 'Departamento', 'Parkside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('262', '262', 'Colombia', 'Cali', 'Departamento', 'Michigan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('263', '263', 'Colombia', 'Medellin', 'Departamento', 'South');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('264', '264', 'Colombia', 'Bogota', 'Departamento', 'American');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('265', '265', 'Colombia', 'Medellin', 'Departamento', 'Carberry');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('266', '266', 'Colombia', 'Cartegena', 'Departamento', 'Maple');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('267', '267', 'Colombia', 'Medellin', 'Departamento', 'Gerald');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('268', '268', 'Colombia', 'Medellin', 'Departamento', 'Quincy');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('269', '269', 'Colombia', 'Bogota', 'Departamento', 'Crescent Oaks');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('270', '270', 'Colombia', 'Medellin', 'Departamento', 'Armistice');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('271', '271', 'Colombia', 'Medellin', 'Departamento', 'Straubel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('272', '272', 'Colombia', 'Cartegena', 'Departamento', 'Graceland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('273', '273', 'Colombia', 'Bogota', 'Departamento', 'Bay');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('274', '274', 'Colombia', 'Cali', 'Departamento', 'Miller');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('275', '275', 'Colombia', 'Medellin', 'Departamento', 'American Ash');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('276', '276', 'Colombia', 'Medellin', 'Departamento', 'Ruskin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('277', '277', 'Colombia', 'Cali', 'Departamento', 'Lakewood Gardens');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('278', '278', 'Colombia', 'Cartegena', 'Departamento', 'Ramsey');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('279', '279', 'Colombia', 'Bogota', 'Departamento', '5th');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('280', '280', 'Colombia', 'Medellin', 'Departamento', 'Redwing');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('281', '281', 'Colombia', 'Bogota', 'Departamento', 'Dapin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('282', '282', 'Colombia', 'Bogota', 'Departamento', 'Huxley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('283', '283', 'Colombia', 'Cartegena', 'Departamento', 'Anniversary');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('284', '284', 'Colombia', 'Cali', 'Departamento', 'Ruskin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('285', '285', 'Colombia', 'Medellin', 'Departamento', 'Crest Line');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('286', '286', 'Colombia', 'Bogota', 'Departamento', 'Fisk');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('287', '287', 'Colombia', 'Bogota', 'Departamento', 'Dovetail');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('288', '288', 'Colombia', 'Bogota', 'Departamento', 'Dawn');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('289', '289', 'Colombia', 'Bogota', 'Departamento', 'Kings');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('290', '290', 'Colombia', 'Bogota', 'Departamento', 'Oriole');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('291', '291', 'Colombia', 'Cali', 'Departamento', 'Hagan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('292', '292', 'Colombia', 'Cartegena', 'Departamento', 'Reinke');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('293', '293', 'Colombia', 'Medellin', 'Departamento', 'Park Meadow');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('294', '294', 'Colombia', 'Bogota', 'Departamento', 'Schiller');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('295', '295', 'Colombia', 'Bogota', 'Departamento', 'Norway Maple');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('296', '296', 'Colombia', 'Cali', 'Departamento', 'Randy');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('297', '297', 'Colombia', 'Medellin', 'Departamento', 'Green');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('298', '298', 'Colombia', 'Cartegena', 'Departamento', 'Mallory');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('299', '299', 'Colombia', 'Bogota', 'Departamento', 'Northview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('300', '300', 'Colombia', 'Cali', 'Departamento', 'Elka');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('301', '301', 'Colombia', 'Cartegena', 'Departamento', 'Calypso');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('302', '302', 'Colombia', 'Cali', 'Departamento', 'Manitowish');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('303', '303', 'Colombia', 'Bogota', 'Departamento', 'Waywood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('304', '304', 'Colombia', 'Medellin', 'Departamento', 'Maywood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('305', '305', 'Colombia', 'Bogota', 'Departamento', 'Algoma');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('306', '306', 'Colombia', 'Cartegena', 'Departamento', 'Utah');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('307', '307', 'Colombia', 'Medellin', 'Departamento', 'Surrey');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('308', '308', 'Colombia', 'Medellin', 'Departamento', 'Sunnyside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('309', '309', 'Colombia', 'Cali', 'Departamento', 'Clove');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('310', '310', 'Colombia', 'Medellin', 'Departamento', 'Almo');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('311', '311', 'Colombia', 'Cartegena', 'Departamento', 'Magdeline');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('312', '312', 'Colombia', 'Cali', 'Departamento', 'Oriole');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('313', '313', 'Colombia', 'Cartegena', 'Departamento', 'Straubel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('314', '314', 'Colombia', 'Medellin', 'Departamento', 'Eggendart');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('315', '315', 'Colombia', 'Cali', 'Departamento', 'Nobel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('316', '316', 'Colombia', 'Medellin', 'Departamento', 'Pearson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('317', '317', 'Colombia', 'Medellin', 'Departamento', 'Dapin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('318', '318', 'Colombia', 'Cartegena', 'Departamento', 'Lakewood Gardens');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('319', '319', 'Colombia', 'Cartegena', 'Departamento', 'Hanson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('320', '320', 'Colombia', 'Medellin', 'Departamento', 'Grim');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('321', '321', 'Colombia', 'Cali', 'Departamento', 'Bowman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('322', '322', 'Colombia', 'Cali', 'Departamento', 'Jenna');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('323', '323', 'Colombia', 'Medellin', 'Departamento', 'Tomscot');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('324', '324', 'Colombia', 'Cartegena', 'Departamento', 'Cascade');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('325', '325', 'Colombia', 'Cali', 'Departamento', 'Bayside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('326', '326', 'Colombia', 'Medellin', 'Departamento', 'Menomonie');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('327', '327', 'Colombia', 'Cartegena', 'Departamento', 'Center');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('328', '328', 'Colombia', 'Cali', 'Departamento', '1st');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('329', '329', 'Colombia', 'Bogota', 'Departamento', 'Independence');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('330', '330', 'Colombia', 'Medellin', 'Departamento', 'Bowman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('331', '331', 'Colombia', 'Cali', 'Departamento', 'Johnson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('332', '332', 'Colombia', 'Bogota', 'Departamento', 'Village');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('333', '333', 'Colombia', 'Cartegena', 'Departamento', 'Karstens');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('334', '334', 'Colombia', 'Medellin', 'Departamento', 'Derek');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('335', '335', 'Colombia', 'Cartegena', 'Departamento', 'Westend');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('336', '336', 'Colombia', 'Cali', 'Departamento', 'Elka');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('337', '337', 'Colombia', 'Bogota', 'Departamento', 'Lake View');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('338', '338', 'Colombia', 'Cali', 'Departamento', 'Portage');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('339', '339', 'Colombia', 'Medellin', 'Departamento', 'Lien');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('340', '340', 'Colombia', 'Cartegena', 'Departamento', 'Northridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('341', '341', 'Colombia', 'Bogota', 'Departamento', 'Amoth');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('342', '342', 'Colombia', 'Cartegena', 'Departamento', 'Springs');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('343', '343', 'Colombia', 'Bogota', 'Departamento', 'Clyde Gallagher');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('344', '344', 'Colombia', 'Cali', 'Departamento', 'Mallard');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('345', '345', 'Colombia', 'Cali', 'Departamento', 'Green Ridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('346', '346', 'Colombia', 'Cartegena', 'Departamento', 'Schmedeman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('347', '347', 'Colombia', 'Cali', 'Departamento', 'Redwing');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('348', '348', 'Colombia', 'Medellin', 'Departamento', 'Aberg');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('349', '349', 'Colombia', 'Cartegena', 'Departamento', 'Burning Wood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('350', '350', 'Colombia', 'Medellin', 'Departamento', 'Darwin');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('351', '351', 'Colombia', 'Cali', 'Departamento', 'Burning Wood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('352', '352', 'Colombia', 'Cali', 'Departamento', 'Hintze');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('353', '353', 'Colombia', 'Medellin', 'Departamento', 'Russell');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('354', '354', 'Colombia', 'Cali', 'Departamento', 'Fairview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('355', '355', 'Colombia', 'Cali', 'Departamento', 'Birchwood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('356', '356', 'Colombia', 'Bogota', 'Departamento', 'Mallard');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('357', '357', 'Colombia', 'Bogota', 'Departamento', 'Swallow');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('358', '358', 'Colombia', 'Cali', 'Departamento', 'Stuart');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('359', '359', 'Colombia', 'Cartegena', 'Departamento', 'Wayridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('360', '360', 'Colombia', 'Bogota', 'Departamento', 'Tennyson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('361', '361', 'Colombia', 'Cartegena', 'Departamento', 'Chinook');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('362', '362', 'Colombia', 'Cali', 'Departamento', 'Warner');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('363', '363', 'Colombia', 'Medellin', 'Departamento', 'Moose');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('364', '364', 'Colombia', 'Cali', 'Departamento', 'Di Loreto');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('365', '365', 'Colombia', 'Cali', 'Departamento', 'Sunfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('366', '366', 'Colombia', 'Cali', 'Departamento', 'Donald');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('367', '367', 'Colombia', 'Cali', 'Departamento', 'Luster');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('368', '368', 'Colombia', 'Bogota', 'Departamento', 'Anniversary');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('369', '369', 'Colombia', 'Cartegena', 'Departamento', 'Fieldstone');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('370', '370', 'Colombia', 'Bogota', 'Departamento', 'Aberg');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('371', '371', 'Colombia', 'Cartegena', 'Departamento', 'Boyd');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('372', '372', 'Colombia', 'Cartegena', 'Departamento', 'Stephen');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('373', '373', 'Colombia', 'Medellin', 'Departamento', 'Muir');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('374', '374', 'Colombia', 'Cartegena', 'Departamento', 'International');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('375', '375', 'Colombia', 'Cartegena', 'Departamento', 'Fieldstone');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('376', '376', 'Colombia', 'Medellin', 'Departamento', 'Hermina');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('377', '377', 'Colombia', 'Cartegena', 'Departamento', 'Barnett');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('378', '378', 'Colombia', 'Bogota', 'Departamento', 'Melby');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('379', '379', 'Colombia', 'Cartegena', 'Departamento', 'Reinke');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('380', '380', 'Colombia', 'Medellin', 'Departamento', 'Bonner');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('381', '381', 'Colombia', 'Medellin', 'Departamento', 'Hooker');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('382', '382', 'Colombia', 'Cali', 'Departamento', 'South');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('383', '383', 'Colombia', 'Bogota', 'Departamento', 'Bunting');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('384', '384', 'Colombia', 'Bogota', 'Departamento', 'Clarendon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('385', '385', 'Colombia', 'Bogota', 'Departamento', 'Melrose');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('386', '386', 'Colombia', 'Cartegena', 'Departamento', 'Fair Oaks');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('387', '387', 'Colombia', 'Bogota', 'Departamento', 'Lawn');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('388', '388', 'Colombia', 'Medellin', 'Departamento', 'Barnett');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('389', '389', 'Colombia', 'Cali', 'Departamento', 'Kenwood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('390', '390', 'Colombia', 'Bogota', 'Departamento', 'Helena');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('391', '391', 'Colombia', 'Cali', 'Departamento', 'Hoepker');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('392', '392', 'Colombia', 'Medellin', 'Departamento', 'Kenwood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('393', '393', 'Colombia', 'Bogota', 'Departamento', 'Sunfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('394', '394', 'Colombia', 'Medellin', 'Departamento', 'Dexter');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('395', '395', 'Colombia', 'Cali', 'Departamento', 'Springview');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('396', '396', 'Colombia', 'Cali', 'Departamento', 'Continental');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('397', '397', 'Colombia', 'Medellin', 'Departamento', '6th');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('398', '398', 'Colombia', 'Bogota', 'Departamento', 'Lerdahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('399', '399', 'Colombia', 'Cali', 'Departamento', 'Meadow Valley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('400', '400', 'Colombia', 'Cali', 'Departamento', 'Eliot');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('401', '401', 'Colombia', 'Cali', 'Departamento', 'Reindahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('402', '402', 'Colombia', 'Cali', 'Departamento', 'Sunnyside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('403', '403', 'Colombia', 'Cartegena', 'Departamento', 'Cardinal');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('404', '404', 'Colombia', 'Cali', 'Departamento', 'Daystar');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('405', '405', 'Colombia', 'Bogota', 'Departamento', 'Westport');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('406', '406', 'Colombia', 'Cartegena', 'Departamento', 'Almo');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('407', '407', 'Colombia', 'Medellin', 'Departamento', 'Schiller');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('408', '408', 'Colombia', 'Bogota', 'Departamento', 'Marcy');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('409', '409', 'Colombia', 'Medellin', 'Departamento', 'Roth');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('410', '410', 'Colombia', 'Medellin', 'Departamento', 'Shelley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('411', '411', 'Colombia', 'Cartegena', 'Departamento', 'Green');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('412', '412', 'Colombia', 'Bogota', 'Departamento', 'Warbler');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('413', '413', 'Colombia', 'Medellin', 'Departamento', 'Main');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('414', '414', 'Colombia', 'Cartegena', 'Departamento', 'Maywood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('415', '415', 'Colombia', 'Cali', 'Departamento', 'Laurel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('416', '416', 'Colombia', 'Bogota', 'Departamento', 'High Crossing');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('417', '417', 'Colombia', 'Cali', 'Departamento', 'Thierer');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('418', '418', 'Colombia', 'Cartegena', 'Departamento', 'Veith');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('419', '419', 'Colombia', 'Medellin', 'Departamento', 'Dahle');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('420', '420', 'Colombia', 'Cali', 'Departamento', 'Mallory');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('421', '421', 'Colombia', 'Bogota', 'Departamento', 'Scoville');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('422', '422', 'Colombia', 'Medellin', 'Departamento', 'Fairfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('423', '423', 'Colombia', 'Cali', 'Departamento', 'Everett');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('424', '424', 'Colombia', 'Medellin', 'Departamento', 'Helena');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('425', '425', 'Colombia', 'Medellin', 'Departamento', 'Northfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('426', '426', 'Colombia', 'Bogota', 'Departamento', 'Huxley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('427', '427', 'Colombia', 'Medellin', 'Departamento', 'Namekagon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('428', '428', 'Colombia', 'Bogota', 'Departamento', 'Briar Crest');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('429', '429', 'Colombia', 'Cartegena', 'Departamento', 'Main');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('430', '430', 'Colombia', 'Bogota', 'Departamento', '5th');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('431', '431', 'Colombia', 'Bogota', 'Departamento', 'Artisan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('432', '432', 'Colombia', 'Medellin', 'Departamento', 'Marquette');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('433', '433', 'Colombia', 'Bogota', 'Departamento', 'Clemons');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('434', '434', 'Colombia', 'Bogota', 'Departamento', 'Mcbride');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('435', '435', 'Colombia', 'Medellin', 'Departamento', 'Riverside');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('436', '436', 'Colombia', 'Cartegena', 'Departamento', 'Lerdahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('437', '437', 'Colombia', 'Cartegena', 'Departamento', 'Redwing');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('438', '438', 'Colombia', 'Medellin', 'Departamento', 'Graceland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('439', '439', 'Colombia', 'Cartegena', 'Departamento', 'Sachs');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('440', '440', 'Colombia', 'Cartegena', 'Departamento', 'Moland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('441', '441', 'Colombia', 'Cali', 'Departamento', 'Weeping Birch');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('442', '442', 'Colombia', 'Medellin', 'Departamento', '1st');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('443', '443', 'Colombia', 'Medellin', 'Departamento', 'Donald');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('444', '444', 'Colombia', 'Cali', 'Departamento', 'Westridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('445', '445', 'Colombia', 'Cartegena', 'Departamento', 'Sloan');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('446', '446', 'Colombia', 'Medellin', 'Departamento', 'Red Cloud');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('447', '447', 'Colombia', 'Medellin', 'Departamento', 'Huxley');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('448', '448', 'Colombia', 'Cartegena', 'Departamento', 'David');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('449', '449', 'Colombia', 'Cali', 'Departamento', 'Nevada');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('450', '450', 'Colombia', 'Cartegena', 'Departamento', 'Moulton');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('451', '451', 'Colombia', 'Medellin', 'Departamento', 'Scoville');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('452', '452', 'Colombia', 'Medellin', 'Departamento', 'Southridge');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('453', '453', 'Colombia', 'Cartegena', 'Departamento', 'Ramsey');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('454', '454', 'Colombia', 'Bogota', 'Departamento', 'Moulton');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('455', '455', 'Colombia', 'Medellin', 'Departamento', 'Sunfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('456', '456', 'Colombia', 'Bogota', 'Departamento', 'Clarendon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('457', '457', 'Colombia', 'Medellin', 'Departamento', 'Fieldstone');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('458', '458', 'Colombia', 'Bogota', 'Departamento', 'Macpherson');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('459', '459', 'Colombia', 'Cartegena', 'Departamento', 'Weeping Birch');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('460', '460', 'Colombia', 'Cartegena', 'Departamento', 'American');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('461', '461', 'Colombia', 'Cali', 'Departamento', 'Westerfield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('462', '462', 'Colombia', 'Medellin', 'Departamento', 'Marcy');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('463', '463', 'Colombia', 'Cartegena', 'Departamento', 'Fisk');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('464', '464', 'Colombia', 'Medellin', 'Departamento', 'Milwaukee');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('465', '465', 'Colombia', 'Bogota', 'Departamento', 'Di Loreto');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('466', '466', 'Colombia', 'Medellin', 'Departamento', 'Nevada');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('467', '467', 'Colombia', 'Bogota', 'Departamento', 'Namekagon');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('468', '468', 'Colombia', 'Medellin', 'Departamento', 'Loomis');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('469', '469', 'Colombia', 'Medellin', 'Departamento', 'Kinsman');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('470', '470', 'Colombia', 'Cartegena', 'Departamento', 'Burrows');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('471', '471', 'Colombia', 'Bogota', 'Departamento', 'Thackeray');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('472', '472', 'Colombia', 'Medellin', 'Departamento', 'Sunbrook');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('473', '473', 'Colombia', 'Cali', 'Departamento', 'Barnett');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('474', '474', 'Colombia', 'Medellin', 'Departamento', 'Sundown');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('475', '475', 'Colombia', 'Bogota', 'Departamento', 'Laurel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('476', '476', 'Colombia', 'Bogota', 'Departamento', 'Shoshone');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('477', '477', 'Colombia', 'Cartegena', 'Departamento', 'Kim');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('478', '478', 'Colombia', 'Medellin', 'Departamento', 'John Wall');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('479', '479', 'Colombia', 'Bogota', 'Departamento', 'Debra');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('480', '480', 'Colombia', 'Bogota', 'Departamento', 'Service');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('481', '481', 'Colombia', 'Medellin', 'Departamento', 'Cardinal');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('482', '482', 'Colombia', 'Medellin', 'Departamento', 'Graceland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('483', '483', 'Colombia', 'Cartegena', 'Departamento', 'Bluestem');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('484', '484', 'Colombia', 'Bogota', 'Departamento', 'Fieldstone');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('485', '485', 'Colombia', 'Cartegena', 'Departamento', 'Thackeray');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('486', '486', 'Colombia', 'Cali', 'Departamento', 'Birchwood');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('487', '487', 'Colombia', 'Medellin', 'Departamento', 'Grim');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('488', '488', 'Colombia', 'Cali', 'Departamento', 'Superior');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('489', '489', 'Colombia', 'Cartegena', 'Departamento', 'Banding');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('490', '490', 'Colombia', 'Cartegena', 'Departamento', 'Maryland');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('491', '491', 'Colombia', 'Medellin', 'Departamento', 'Raven');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('492', '492', 'Colombia', 'Medellin', 'Departamento', 'Jay');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('493', '493', 'Colombia', 'Bogota', 'Departamento', 'Packers');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('494', '494', 'Colombia', 'Cartegena', 'Departamento', 'Declaration');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('495', '495', 'Colombia', 'Cali', 'Departamento', 'Scofield');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('496', '496', 'Colombia', 'Medellin', 'Departamento', 'Reindahl');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('497', '497', 'Colombia', 'Cali', 'Departamento', 'Kipling');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('498', '498', 'Colombia', 'Medellin', 'Departamento', 'Straubel');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('499', '499', 'Colombia', 'Cali', 'Departamento', 'Superior');
INSERT INTO DireccionesUsuarios (IDDireccion, IDUsuario, Pais, Ciudad, Departamento, Descripcion) VALUES ('500', '500', 'Colombia', 'Cartegena', 'Departamento', 'Morning');
