INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('1', '227', 'Colombia', 'Cartegena', 'Departamento', 'Waywood');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('2', '228', 'Colombia', 'Bogota', 'Departamento', 'Jackson');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('3', '226', 'Colombia', 'Bogota', 'Departamento', 'Fairview');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('4', '227', 'Colombia', 'Medellin', 'Departamento', 'Loftsgordon');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('5', '228', 'Colombia', 'Bogota', 'Departamento', 'Golf');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('6', '226', 'Colombia', 'Medellin', 'Departamento', 'Haas');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('7', '227', 'Colombia', 'Bogota', 'Departamento', 'Stephen');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('8', '228', 'Colombia', 'Cartegena', 'Departamento', 'Village Green');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('9', '226', 'Colombia', 'Cali', 'Departamento', 'Hagan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('10', '227', 'Colombia', 'Bogota', 'Departamento', 'Waywood');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('11', '228', 'Colombia', 'Bogota', 'Departamento', 'Corben');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('12', '226', 'Colombia', 'Bogota', 'Departamento', 'Fairview');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('13', '227', 'Colombia', 'Cali', 'Departamento', 'Merrick');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('14', '228', 'Colombia', 'Bogota', 'Departamento', 'Dryden');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('15', '226', 'Colombia', 'Bogota', 'Departamento', 'Annamark');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('16', '227', 'Colombia', 'Medellin', 'Departamento', 'Bluejay');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('17', '228', 'Colombia', 'Cartegena', 'Departamento', 'Glacier Hill');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('18', '226', 'Colombia', 'Bogota', 'Departamento', 'Schmedeman');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('19', '227', 'Colombia', 'Bogota', 'Departamento', 'Charing Cross');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('20', '228', 'Colombia', 'Medellin', 'Departamento', 'Harbort');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('21', '226', 'Colombia', 'Cartegena', 'Departamento', 'Kim');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('22', '227', 'Colombia', 'Cartegena', 'Departamento', 'Texas');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('23', '228', 'Colombia', 'Cali', 'Departamento', 'Kingsford');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('24', '226', 'Colombia', 'Cali', 'Departamento', 'Holy Cross');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('25', '227', 'Colombia', 'Medellin', 'Departamento', 'Almo');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('26', '228', 'Colombia', 'Cali', 'Departamento', 'Armistice');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('27', '226', 'Colombia', 'Bogota', 'Departamento', 'Calypso');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('28', '227', 'Colombia', 'Medellin', 'Departamento', 'Huxley');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('29', '228', 'Colombia', 'Cartegena', 'Departamento', 'Heffernan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('30', '226', 'Colombia', 'Bogota', 'Departamento', 'Vermont');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('31', '227', 'Colombia', 'Bogota', 'Departamento', 'Hoard');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('32', '228', 'Colombia', 'Cartegena', 'Departamento', 'American');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('33', '226', 'Colombia', 'Cali', 'Departamento', 'Grim');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('34', '227', 'Colombia', 'Medellin', 'Departamento', 'Luster');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('35', '228', 'Colombia', 'Cali', 'Departamento', 'Ruskin');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('36', '226', 'Colombia', 'Bogota', 'Departamento', 'Utah');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('37', '227', 'Colombia', 'Bogota', 'Departamento', 'Transport');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('38', '228', 'Colombia', 'Medellin', 'Departamento', 'Bluestem');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('39', '226', 'Colombia', 'Medellin', 'Departamento', 'Northwestern');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('40', '227', 'Colombia', 'Cali', 'Departamento', 'Sunfield');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('41', '228', 'Colombia', 'Cali', 'Departamento', 'Kipling');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('42', '226', 'Colombia', 'Cali', 'Departamento', 'Iowa');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('43', '227', 'Colombia', 'Medellin', 'Departamento', 'Arizona');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('44', '228', 'Colombia', 'Cali', 'Departamento', 'Havey');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('45', '226', 'Colombia', 'Cali', 'Departamento', 'Holmberg');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('46', '227', 'Colombia', 'Medellin', 'Departamento', 'Bowman');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('47', '228', 'Colombia', 'Cali', 'Departamento', 'Corscot');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('48', '226', 'Colombia', 'Medellin', 'Departamento', 'Oak Valley');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('49', '227', 'Colombia', 'Medellin', 'Departamento', 'Blue Bill Park');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('50', '228', 'Colombia', 'Cali', 'Departamento', 'Lakeland');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('51', '226', 'Colombia', 'Bogota', 'Departamento', 'Lindbergh');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('52', '227', 'Colombia', 'Cali', 'Departamento', 'Westport');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('53', '228', 'Colombia', 'Medellin', 'Departamento', 'Katie');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('54', '226', 'Colombia', 'Bogota', 'Departamento', 'Ronald Regan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('55', '227', 'Colombia', 'Cali', 'Departamento', 'Brentwood');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('56', '228', 'Colombia', 'Medellin', 'Departamento', 'Carpenter');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('57', '226', 'Colombia', 'Cartegena', 'Departamento', 'Bunting');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('58', '227', 'Colombia', 'Bogota', 'Departamento', 'Buell');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('59', '228', 'Colombia', 'Cartegena', 'Departamento', 'Westridge');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('60', '226', 'Colombia', 'Bogota', 'Departamento', 'School');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('61', '227', 'Colombia', 'Cartegena', 'Departamento', 'Michigan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('62', '228', 'Colombia', 'Cartegena', 'Departamento', 'Arrowood');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('63', '226', 'Colombia', 'Cali', 'Departamento', 'Bonner');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('64', '227', 'Colombia', 'Cali', 'Departamento', 'Summerview');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('65', '228', 'Colombia', 'Bogota', 'Departamento', '7th');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('66', '226', 'Colombia', 'Medellin', 'Departamento', 'Beilfuss');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('67', '227', 'Colombia', 'Cali', 'Departamento', 'Valley Edge');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('68', '228', 'Colombia', 'Cartegena', 'Departamento', 'Buhler');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('69', '226', 'Colombia', 'Medellin', 'Departamento', 'Sommers');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('70', '227', 'Colombia', 'Bogota', 'Departamento', 'Clyde Gallagher');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('71', '228', 'Colombia', 'Bogota', 'Departamento', 'Heffernan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('72', '226', 'Colombia', 'Medellin', 'Departamento', 'Havey');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('73', '227', 'Colombia', 'Cartegena', 'Departamento', 'Sage');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('74', '228', 'Colombia', 'Cali', 'Departamento', 'American Ash');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('75', '226', 'Colombia', 'Bogota', 'Departamento', 'Reindahl');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('76', '227', 'Colombia', 'Bogota', 'Departamento', 'Florence');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('77', '228', 'Colombia', 'Cali', 'Departamento', 'Dryden');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('78', '226', 'Colombia', 'Cartegena', 'Departamento', 'Jenifer');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('79', '227', 'Colombia', 'Cali', 'Departamento', 'Lake View');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('80', '228', 'Colombia', 'Medellin', 'Departamento', 'Clemons');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('81', '226', 'Colombia', 'Medellin', 'Departamento', 'Elgar');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('82', '227', 'Colombia', 'Cartegena', 'Departamento', 'Roth');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('83', '228', 'Colombia', 'Cali', 'Departamento', 'Center');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('84', '226', 'Colombia', 'Medellin', 'Departamento', 'Ridgeway');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('85', '227', 'Colombia', 'Cartegena', 'Departamento', 'Derek');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('86', '228', 'Colombia', 'Bogota', 'Departamento', 'Pankratz');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('87', '226', 'Colombia', 'Medellin', 'Departamento', 'Rusk');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('88', '227', 'Colombia', 'Cali', 'Departamento', 'Eastlawn');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('89', '228', 'Colombia', 'Bogota', 'Departamento', 'Cherokee');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('90', '226', 'Colombia', 'Cali', 'Departamento', 'Lindbergh');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('91', '227', 'Colombia', 'Cartegena', 'Departamento', 'Blaine');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('92', '228', 'Colombia', 'Medellin', 'Departamento', 'Carberry');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('93', '226', 'Colombia', 'Bogota', 'Departamento', 'Stephen');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('94', '227', 'Colombia', 'Medellin', 'Departamento', 'Comanche');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('95', '228', 'Colombia', 'Medellin', 'Departamento', 'Transport');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('96', '226', 'Colombia', 'Cali', 'Departamento', 'Heffernan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('97', '227', 'Colombia', 'Cali', 'Departamento', 'Judy');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('98', '228', 'Colombia', 'Cali', 'Departamento', 'Muir');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('99', '226', 'Colombia', 'Medellin', 'Departamento', 'Mitchell');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('100', '227', 'Colombia', 'Bogota', 'Departamento', 'Autumn Leaf');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('101', '228', 'Colombia', 'Medellin', 'Departamento', 'Nelson');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('102', '226', 'Colombia', 'Medellin', 'Departamento', 'Bluestem');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('103', '227', 'Colombia', 'Medellin', 'Departamento', 'Maple');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('104', '228', 'Colombia', 'Bogota', 'Departamento', 'Elka');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('105', '226', 'Colombia', 'Medellin', 'Departamento', 'Sage');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('106', '227', 'Colombia', 'Bogota', 'Departamento', 'Lotheville');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('107', '228', 'Colombia', 'Medellin', 'Departamento', 'Atwood');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('108', '226', 'Colombia', 'Cali', 'Departamento', 'Ronald Regan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('109', '227', 'Colombia', 'Cali', 'Departamento', 'Kensington');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('110', '228', 'Colombia', 'Medellin', 'Departamento', 'Columbus');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('111', '226', 'Colombia', 'Medellin', 'Departamento', 'Johnson');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('112', '227', 'Colombia', 'Cartegena', 'Departamento', 'Linden');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('113', '228', 'Colombia', 'Cali', 'Departamento', 'Mariners Cove');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('114', '226', 'Colombia', 'Bogota', 'Departamento', 'Randy');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('115', '227', 'Colombia', 'Cartegena', 'Departamento', 'Fuller');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('116', '228', 'Colombia', 'Cartegena', 'Departamento', 'Sutherland');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('117', '226', 'Colombia', 'Cali', 'Departamento', 'Grim');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('118', '227', 'Colombia', 'Bogota', 'Departamento', 'Toban');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('119', '228', 'Colombia', 'Bogota', 'Departamento', 'Continental');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('120', '226', 'Colombia', 'Cali', 'Departamento', 'Service');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('121', '227', 'Colombia', 'Bogota', 'Departamento', 'Hanover');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('122', '228', 'Colombia', 'Cali', 'Departamento', 'Upham');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('123', '226', 'Colombia', 'Cartegena', 'Departamento', 'Kropf');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('124', '227', 'Colombia', 'Cartegena', 'Departamento', 'Sloan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('125', '228', 'Colombia', 'Bogota', 'Departamento', 'Dennis');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('126', '226', 'Colombia', 'Medellin', 'Departamento', 'Dwight');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('127', '227', 'Colombia', 'Medellin', 'Departamento', 'Cordelia');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('128', '228', 'Colombia', 'Bogota', 'Departamento', 'Commercial');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('129', '226', 'Colombia', 'Cartegena', 'Departamento', 'Goodland');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('130', '227', 'Colombia', 'Bogota', 'Departamento', '5th');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('131', '228', 'Colombia', 'Medellin', 'Departamento', 'Dorton');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('132', '226', 'Colombia', 'Medellin', 'Departamento', 'Fuller');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('133', '227', 'Colombia', 'Medellin', 'Departamento', 'Raven');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('134', '228', 'Colombia', 'Bogota', 'Departamento', 'Hoffman');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('135', '226', 'Colombia', 'Medellin', 'Departamento', '2nd');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('136', '227', 'Colombia', 'Cali', 'Departamento', 'Shelley');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('137', '228', 'Colombia', 'Bogota', 'Departamento', 'Logan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('138', '226', 'Colombia', 'Cartegena', 'Departamento', 'Clove');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('139', '227', 'Colombia', 'Cali', 'Departamento', 'Sutteridge');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('140', '228', 'Colombia', 'Bogota', 'Departamento', 'Cody');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('141', '226', 'Colombia', 'Cali', 'Departamento', 'Prairie Rose');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('142', '227', 'Colombia', 'Bogota', 'Departamento', 'Mcbride');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('143', '228', 'Colombia', 'Cartegena', 'Departamento', 'Express');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('144', '226', 'Colombia', 'Cali', 'Departamento', 'Eagan');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('145', '227', 'Colombia', 'Cali', 'Departamento', 'Goodland');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('146', '228', 'Colombia', 'Cali', 'Departamento', 'Prairieview');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('147', '226', 'Colombia', 'Cali', 'Departamento', 'International');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('148', '227', 'Colombia', 'Cartegena', 'Departamento', 'Pawling');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('149', '228', 'Colombia', 'Bogota', 'Departamento', 'John Wall');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('150', '226', 'Colombia', 'Medellin', 'Departamento', 'Cordelia');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('151', '227', 'Colombia', 'Bogota', 'Departamento', 'Lillian');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('152', '228', 'Colombia', 'Medellin', 'Departamento', 'Corry');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('153', '226', 'Colombia', 'Medellin', 'Departamento', 'Weeping Birch');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('154', '227', 'Colombia', 'Cartegena', 'Departamento', 'Morningstar');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('155', '228', 'Colombia', 'Medellin', 'Departamento', 'Mccormick');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('156', '226', 'Colombia', 'Cartegena', 'Departamento', 'Tony');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('157', '227', 'Colombia', 'Bogota', 'Departamento', 'Stuart');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('158', '228', 'Colombia', 'Bogota', 'Departamento', 'Eggendart');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('159', '226', 'Colombia', 'Cartegena', 'Departamento', 'Monterey');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('160', '227', 'Colombia', 'Bogota', 'Departamento', 'Karstens');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('161', '228', 'Colombia', 'Cali', 'Departamento', 'Badeau');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('162', '226', 'Colombia', 'Medellin', 'Departamento', 'Troy');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('163', '227', 'Colombia', 'Cali', 'Departamento', 'Kensington');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('164', '228', 'Colombia', 'Bogota', 'Departamento', 'Anniversary');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('165', '226', 'Colombia', 'Bogota', 'Departamento', 'Golf');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('166', '227', 'Colombia', 'Medellin', 'Departamento', 'Little Fleur');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('167', '228', 'Colombia', 'Cartegena', 'Departamento', 'Mcguire');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('168', '226', 'Colombia', 'Cartegena', 'Departamento', 'Vahlen');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('169', '227', 'Colombia', 'Bogota', 'Departamento', 'Shasta');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('170', '228', 'Colombia', 'Bogota', 'Departamento', 'Merry');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('171', '226', 'Colombia', 'Cali', 'Departamento', 'Sunnyside');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('172', '227', 'Colombia', 'Medellin', 'Departamento', 'Anhalt');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('173', '228', 'Colombia', 'Cali', 'Departamento', 'Hooker');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('174', '226', 'Colombia', 'Bogota', 'Departamento', 'Valley Edge');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('175', '227', 'Colombia', 'Medellin', 'Departamento', 'Doe Crossing');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('176', '228', 'Colombia', 'Bogota', 'Departamento', 'Meadow Valley');
INSERT INTO DireccionesEstablecimientos (IDDireccion, IDEstablecimiento, Pais, Ciudad, Departamento, Descripcion) VALUES ('177', '226', 'Colombia', 'Bogota', 'Departamento', 'Thierer');
