INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Valve Corporation','Valve Corporation@mail.com','5155805','8017612','https://www.Valve Corporation.com','proveedor','Valve Corporation');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Introversion Software','Introversion Software@mail.com','9486411','6222908','https://www.Introversion Software.com','proveedor','Introversion Software');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Strategy First','Strategy First@mail.com','4917850','6204407','https://www.Strategy First.com','proveedor','Strategy First');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Midway Games','Midway Games@mail.com','5352752','1132681','https://www.Midway Games.com','proveedor','Midway Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Meridian4','Meridian4@mail.com','4731778','4369791','https://www.Meridian4.com','proveedor','Meridian4');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Activision','Activision@mail.com','4643740','1849489','https://www.Activision.com','proveedor','Activision');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Infogrames','Infogrames@mail.com','5188235','4287287','https://www.Infogrames.com','proveedor','Infogrames');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Enlight','Enlight@mail.com','3319380','6814873','https://www.Enlight.com','proveedor','Enlight');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Topware Interactive','Topware Interactive@mail.com','3619370','8163508','https://www.Topware Interactive.com','proveedor','Topware Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Majesco Entertainment','Majesco Entertainment@mail.com','7567925','9077277','https://www.Majesco Entertainment.com','proveedor','Majesco Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Funkitron','Funkitron@mail.com','3748734','8116034','https://www.Funkitron.com','proveedor','Funkitron');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('cdv','cdv@mail.com','8449334','5026666','https://www.cdv.com','proveedor','cdv');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('2K Games','2K Games@mail.com','2397258','7814638','https://www.2K Games.com','proveedor','2K Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Ubisoft','Ubisoft@mail.com','3079036','9308655','https://www.Ubisoft.com','proveedor','Ubisoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sega','Sega@mail.com','6620543','9683081','https://www.Sega.com','proveedor','Sega');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Eidos Interactive','Eidos Interactive@mail.com','3912672','9710186','https://www.Eidos Interactive.com','proveedor','Eidos Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Funcom','Funcom@mail.com','9033115','7724992','https://www.Funcom.com','proveedor','Funcom');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Popcap Games','Popcap Games@mail.com','9146624','5345740','https://www.Popcap Games.com','proveedor','Popcap Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Focus Home Interactive','Focus Home Interactive@mail.com','1315861','5161850','https://www.Focus Home Interactive.com','proveedor','Focus Home Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Capcom','Capcom@mail.com','6662727','6067876','https://www.Capcom.com','proveedor','Capcom');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Telltale Games','Telltale Games@mail.com','6724856','6408659','https://www.Telltale Games.com','proveedor','Telltale Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('THQ','THQ@mail.com','2888478','5131562','https://www.THQ.com','proveedor','THQ');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Codemasters','Codemasters@mail.com','4190445','1551556','https://www.Codemasters.com','proveedor','Codemasters');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('SEGA','SEGA@mail.com','1228310','2094549','https://www.SEGA.com','proveedor','SEGA');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Rockstar Games','Rockstar Games@mail.com','2192668','9418288','https://www.Rockstar Games.com','proveedor','Rockstar Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Epic Games','Epic Games@mail.com','8109301','1669230','https://www.Epic Games.com','proveedor','Epic Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Nunchuck Games','Nunchuck Games@mail.com','3406982','4296034','https://www.Nunchuck Games.com','proveedor','Nunchuck Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('MumboJumbo','MumboJumbo@mail.com','3857431','3144618','https://www.MumboJumbo.com','proveedor','MumboJumbo');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Silver Sphere Studios','Silver Sphere Studios@mail.com','5458122','6775985','https://www.Silver Sphere Studios.com','proveedor','Silver Sphere Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('GT Interactive','GT Interactive@mail.com','6155429','1922218','https://www.GT Interactive.com','proveedor','GT Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Electronic Arts','Electronic Arts@mail.com','5767335','4175563','https://www.Electronic Arts.com','proveedor','Electronic Arts');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Warner Bros','Warner Bros@mail.com','2742026','4269119','https://www.Warner Bros.com','proveedor','Warner Bros.');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('2D Boy','2D Boy@mail.com','7455243','4713502','https://www.2D Boy.com','proveedor','2D Boy');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Deep Silver','Deep Silver@mail.com','5617707','2481514','https://www.Deep Silver.com','proveedor','Deep Silver');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bethesda Softworks','Bethesda Softworks@mail.com','6748546','2720397','https://www.Bethesda Softworks.com','proveedor','Bethesda Softworks');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Paradox Interactive','Paradox Interactive@mail.com','3623108','3467748','https://www.Paradox Interactive.com','proveedor','Paradox Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Hidden Path Entertainment','Hidden Path Entertainment@mail.com','9549075','1960867','https://www.Hidden Path Entertainment.com','proveedor','Hidden Path Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Viva Media','Viva Media@mail.com','1600147','6177111','https://www.Viva Media.com','proveedor','Viva Media');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bit Blot','Bit Blot@mail.com','3230294','7424824','https://www.Bit Blot.com','proveedor','Bit Blot');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sony Online Entertainment','Sony Online Entertainment@mail.com','2059312','9903544','https://www.Sony Online Entertainment.com','proveedor','Sony Online Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Inventive Dingo','Inventive Dingo@mail.com','6103851','2372832','https://www.Inventive Dingo.com','proveedor','Inventive Dingo');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Oxeye Game Studio','Oxeye Game Studio@mail.com','6924074','7061028','https://www.Oxeye Game Studio.com','proveedor','Oxeye Game Studio');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Miniclip','Miniclip@mail.com','3920480','8704597','https://www.Miniclip.com','proveedor','Miniclip');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('N3VRF41L','N3VRF41L@mail.com','3846891','6178024','https://www.N3VRF41L.com','proveedor','N3VRF41L');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Basilink Games','Basilink Games@mail.com','5201180','9211387','https://www.Basilink Games.com','proveedor','Basilink Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Three Donkeys','Three Donkeys@mail.com','1004490','1935649','https://www.Three Donkeys.com','proveedor','Three Donkeys');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('D3','D3@mail.com','2954560','8304496','https://www.D3.com','proveedor','D3');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Kalypso Media','Kalypso Media@mail.com','6728033','1640497','https://www.Kalypso Media.com','proveedor','Kalypso Media');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Konami','Konami@mail.com','9939668','6124506','https://www.Konami.com','proveedor','Konami');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Frictional Games','Frictional Games@mail.com','7438182','3404827','https://www.Frictional Games.com','proveedor','Frictional Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Tale of Tales','Tale of Tales@mail.com','8032529','2827331','https://www.Tale of Tales.com','proveedor','Tale of Tales');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('CCP','CCP@mail.com','1783575','2193432','https://www.CCP.com','proveedor','CCP');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Twisted Pixel Games','Twisted Pixel Games@mail.com','6895036','7695628','https://www.Twisted Pixel Games.com','proveedor','Twisted Pixel Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Paleo Entertainment','Paleo Entertainment@mail.com','2086715','7317596','https://www.Paleo Entertainment.com','proveedor','Paleo Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('1C Company','1C Company@mail.com','3791678','2985279','https://www.1C Company.com','proveedor','1C Company');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Elecorn','Elecorn@mail.com','3466685','8847597','https://www.Elecorn.com','proveedor','Elecorn');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Llamasoft','Llamasoft@mail.com','9911185','3796950','https://www.Llamasoft.com','proveedor','Llamasoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Red Rocket Games','Red Rocket Games@mail.com','8696060','7714047','https://www.Red Rocket Games.com','proveedor','Red Rocket Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Warner Bros. Interactive Entertainment','Warner Bros. Interactive Entertainment@mail.com','4922682','1995125','https://www.Warner Bros. Interactive Entertainment.com','proveedor','Warner Bros. Interactive Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Aspyr Media','Aspyr Media@mail.com','4757251','8281987','https://www.Aspyr Media.com','proveedor','Aspyr Media');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Evolved Games','Evolved Games@mail.com','2070600','9203532','https://www.Evolved Games.com','proveedor','Evolved Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('DTP Entertainment','DTP Entertainment@mail.com','8978704','7588385','https://www.DTP Entertainment.com','proveedor','DTP Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Broken Rules','Broken Rules@mail.com','5046087','8965267','https://www.Broken Rules.com','proveedor','Broken Rules');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Square Enix','Square Enix@mail.com','6466320','5999638','https://www.Square Enix.com','proveedor','Square Enix');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Number None','Number None@mail.com','1936250','2104981','https://www.Number None.com','proveedor','Number None');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('ACE Team','ACE Team@mail.com','9242198','1311185','https://www.ACE Team.com','proveedor','ACE Team');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('NCsoft','NCsoft@mail.com','6286486','7022696','https://www.NCsoft.com','proveedor','NCsoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Mezmer Games','Mezmer Games@mail.com','7258176','5802099','https://www.Mezmer Games.com','proveedor','Mezmer Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('TopWare Interactive','TopWare Interactive@mail.com','3031836','7873424','https://www.TopWare Interactive.com','proveedor','TopWare Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('SouthPeak Interactive','SouthPeak Interactive@mail.com','8569812','8907428','https://www.SouthPeak Interactive.com','proveedor','SouthPeak Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Atari','Atari@mail.com','4930377','9508805','https://www.Atari.com','proveedor','Atari');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Kloonigames','Kloonigames@mail.com','5597676','6664051','https://www.Kloonigames.com','proveedor','Kloonigames');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Last Day of Work','Last Day of Work@mail.com','2052948','4432224','https://www.Last Day of Work.com','proveedor','Last Day of Work');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Tripwire Interactive','Tripwire Interactive@mail.com','5394949','2505561','https://www.Tripwire Interactive.com','proveedor','Tripwire Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('boll AG','boll AG@mail.com','2586256','8764003','https://www.boll AG.com','proveedor','boll AG');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Warner Brothers Entertainment','Warner Brothers Entertainment@mail.com','2367922','1884123','https://www.Warner Brothers Entertainment.com','proveedor','Warner Brothers Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sigma Team','Sigma Team@mail.com','2201283','9980029','https://www.Sigma Team.com','proveedor','Sigma Team');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Enlight Entertainment','Enlight Entertainment@mail.com','7902168','4438784','https://www.Enlight Entertainment.com','proveedor','Enlight Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Erik Sved?§ng','Erik Sved?§ng@mail.com','7190673','1912085','https://www.Erik Sved?§ng.com','proveedor','Erik Sved?§ng');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('SaintXi','SaintXi@mail.com','7982916','5829899','https://www.SaintXi.com','proveedor','SaintXi');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('RailSimulator.com','RailSimulator.com@mail.com','4552051','1063255','https://www.RailSimulator.com.com','proveedor','RailSimulator.com');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('US Army','US Army@mail.com','1583868','5650737','https://www.US Army.com','proveedor','US Army');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('NovaLogic','NovaLogic@mail.com','2764267','8765099','https://www.NovaLogic.com','proveedor','NovaLogic');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('City Interactive','City Interactive@mail.com','4216280','9793775','https://www.City Interactive.com','proveedor','City Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Rebellion Developments','Rebellion Developments@mail.com','5941502','7583983','https://www.Rebellion Developments.com','proveedor','Rebellion Developments');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('EA','EA@mail.com','6673707','1634799','https://www.EA.com','proveedor','EA');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bohemia Interactive Studio','Bohemia Interactive Studio@mail.com','9772465','1455343','https://www.Bohemia Interactive Studio.com','proveedor','Bohemia Interactive Studio');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Atlus','Atlus@mail.com','5312593','1937851','https://www.Atlus.com','proveedor','Atlus');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Frozenbyte','Frozenbyte@mail.com','5695254','9715411','https://www.Frozenbyte.com','proveedor','Frozenbyte');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Shrapnel Games','Shrapnel Games@mail.com','3144438','3433153','https://www.Shrapnel Games.com','proveedor','Shrapnel Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('LucasArts','LucasArts@mail.com','6730094','4845269','https://www.LucasArts.com','proveedor','LucasArts');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Her Interactive','Her Interactive@mail.com','7206814','5976342','https://www.Her Interactive.com','proveedor','Her Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sandlot Games','Sandlot Games@mail.com','3332677','9527901','https://www.Sandlot Games.com','proveedor','Sandlot Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Hemisphere Games','Hemisphere Games@mail.com','7626726','8306204','https://www.Hemisphere Games.com','proveedor','Hemisphere Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Omni Systems','Omni Systems@mail.com','7155295','7134896','https://www.Omni Systems.com','proveedor','Omni Systems');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Black Jacket Studios','Black Jacket Studios@mail.com','9890375','6842250','https://www.Black Jacket Studios.com','proveedor','Black Jacket Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Futuremark Games Studio','Futuremark Games Studio@mail.com','9580319','6215709','https://www.Futuremark Games Studio.com','proveedor','Futuremark Games Studio');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Croteam','Croteam@mail.com','6366691','3283818','https://www.Croteam.com','proveedor','Croteam');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Neocore Games','Neocore Games@mail.com','9966959','5893724','https://www.Neocore Games.com','proveedor','Neocore Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Virgin Interactive','Virgin Interactive@mail.com','8903658','8213135','https://www.Virgin Interactive.com','proveedor','Virgin Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('JoWood Productions','JoWood Productions@mail.com','4107514','5641849','https://www.JoWood Productions.com','proveedor','JoWood Productions');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Exor Studios','Exor Studios@mail.com','8809067','8103764','https://www.Exor Studios.com','proveedor','Exor Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Nimbly Games','Nimbly Games@mail.com','7230916','1311829','https://www.Nimbly Games.com','proveedor','Nimbly Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Headup Games','Headup Games@mail.com','8403037','9455844','https://www.Headup Games.com','proveedor','Headup Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('ND Games','ND Games@mail.com','9558111','3849893','https://www.ND Games.com','proveedor','ND Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Runic Games','Runic Games@mail.com','2967229','1239951','https://www.Runic Games.com','proveedor','Runic Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('TWELVE','TWELVE@mail.com','9167432','6970672','https://www.TWELVE.com','proveedor','TWELVE');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Gaijin Entertainment','Gaijin Entertainment@mail.com','5497492','6819302','https://www.Gaijin Entertainment.com','proveedor','Gaijin Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Nimblebit','Nimblebit@mail.com','9194096','8671254','https://www.Nimblebit.com','proveedor','Nimblebit');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Arcen Games','Arcen Games@mail.com','9911460','3972851','https://www.Arcen Games.com','proveedor','Arcen Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Fox Interactive','Fox Interactive@mail.com','9927968','4854108','https://www.Fox Interactive.com','proveedor','Fox Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Ludosity Interactive','Ludosity Interactive@mail.com','8813322','1494594','https://www.Ludosity Interactive.com','proveedor','Ludosity Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('SouthPeak Games','SouthPeak Games@mail.com','8603823','3232025','https://www.SouthPeak Games.com','proveedor','SouthPeak Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Hi-Rez Studios','Hi-Rez Studios@mail.com','3618048','8998981','https://www.Hi-Rez Studios.com','proveedor','Hi-Rez Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('FireSky','FireSky@mail.com','3904585','7601687','https://www.FireSky.com','proveedor','FireSky');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Cadenza Interactive','Cadenza Interactive@mail.com','7296860','4429420','https://www.Cadenza Interactive.com','proveedor','Cadenza Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Viva Media, Koch Media','Viva Media, Koch Media@mail.com','1993857','8969203','https://www.Viva Media, Koch Media.com','proveedor','Viva Media, Koch Media');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Devolver Digital','Devolver Digital@mail.com','5992152','9711818','https://www.Devolver Digital.com','proveedor','Devolver Digital');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Team17','Team17@mail.com','8627881','4203819','https://www.Team17.com','proveedor','Team17');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Doctor Entertainment','Doctor Entertainment@mail.com','1263922','9100796','https://www.Doctor Entertainment.com','proveedor','Doctor Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Muzzy Lane Software','Muzzy Lane Software@mail.com','5459167','2496704','https://www.Muzzy Lane Software.com','proveedor','Muzzy Lane Software');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sonic Boom Games','Sonic Boom Games@mail.com','8559380','5806341','https://www.Sonic Boom Games.com','proveedor','Sonic Boom Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('N3V Games','N3V Games@mail.com','9962005','3128132','https://www.N3V Games.com','proveedor','N3V Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('JoWooD Entertainment','JoWooD Entertainment@mail.com','9111418','3099989','https://www.JoWooD Entertainment.com','proveedor','JoWooD Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Cyan Worlds','Cyan Worlds@mail.com','9900580','3384335','https://www.Cyan Worlds.com','proveedor','Cyan Worlds');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('4sdk','4sdk@mail.com','6920658','4403428','https://www.4sdk.com','proveedor','4sdk');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('P2 Games','P2 Games@mail.com','6401403','4182160','https://www.P2 Games.com','proveedor','P2 Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Namco Networks America','Namco Networks America@mail.com','9585490','4682954','https://www.Namco Networks America.com','proveedor','Namco Networks America');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Dedication Games','Dedication Games@mail.com','8273267','7329878','https://www.Dedication Games.com','proveedor','Dedication Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('NCSoft','NCSoft@mail.com','1656426','4148396','https://www.NCSoft.com','proveedor','NCSoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('BigSims.com','BigSims.com@mail.com','7103184','4102558','https://www.BigSims.com.com','proveedor','BigSims.com');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Team 17','Team 17@mail.com','2708788','3984565','https://www.Team 17.com','proveedor','Team 17');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('OneBigGame','OneBigGame@mail.com','4141335','5879693','https://www.OneBigGame.com','proveedor','OneBigGame');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Carpe Fulgur LLC','Carpe Fulgur LLC@mail.com','6155255','5742822','https://www.Carpe Fulgur LLC.com','proveedor','Carpe Fulgur LLC');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('exosyphen studios','exosyphen studios@mail.com','9299438','8580532','https://www.exosyphen studios.com','proveedor','exosyphen studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Paramount Digital Entertainment','Paramount Digital Entertainment@mail.com','4621243','4588126','https://www.Paramount Digital Entertainment.com','proveedor','Paramount Digital Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Subsoap','Subsoap@mail.com','3238795','3252862','https://www.Subsoap.com','proveedor','Subsoap');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Kalypso Media Digital','Kalypso Media Digital@mail.com','3117838','3617428','https://www.Kalypso Media Digital.com','proveedor','Kalypso Media Digital');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Blind Mind Studios','Blind Mind Studios@mail.com','3400816','8107565','https://www.Blind Mind Studios.com','proveedor','Blind Mind Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Lunar Giant Studios','Lunar Giant Studios@mail.com','3505131','3879554','https://www.Lunar Giant Studios.com','proveedor','Lunar Giant Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Over the Top Games','Over the Top Games@mail.com','1994265','4191901','https://www.Over the Top Games.com','proveedor','Over the Top Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Blendo Games','Blendo Games@mail.com','6555131','6717149','https://www.Blendo Games.com','proveedor','Blendo Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('2K Sports','2K Sports@mail.com','5863504','8779959','https://www.2K Sports.com','proveedor','2K Sports');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('2K Play','2K Play@mail.com','7942510','1783381','https://www.2K Play.com','proveedor','2K Play');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Wolfire Games','Wolfire Games@mail.com','8197963','7104689','https://www.Wolfire Games.com','proveedor','Wolfire Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Paradox Entertainment','Paradox Entertainment@mail.com','3733069','4509418','https://www.Paradox Entertainment.com','proveedor','Paradox Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('GrendelGames','GrendelGames@mail.com','6625448','6654298','https://www.GrendelGames.com','proveedor','GrendelGames');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Egosoft','Egosoft@mail.com','1562104','6087460','https://www.Egosoft.com','proveedor','Egosoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Youdagames','Youdagames@mail.com','2591307','1027178','https://www.Youdagames.com','proveedor','Youdagames');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Triumph Studios','Triumph Studios@mail.com','9168077','2041175','https://www.Triumph Studios.com','proveedor','Triumph Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Stickmen Studios','Stickmen Studios@mail.com','5916062','7700885','https://www.Stickmen Studios.com','proveedor','Stickmen Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Dmytry Lavrov','Dmytry Lavrov@mail.com','2001005','1300846','https://www.Dmytry Lavrov.com','proveedor','Dmytry Lavrov');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Firemint','Firemint@mail.com','9203134','5523736','https://www.Firemint.com','proveedor','Firemint');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Team Meat','Team Meat@mail.com','2564126','2107836','https://www.Team Meat.com','proveedor','Team Meat');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Ronimo Games','Ronimo Games@mail.com','5234769','6056476','https://www.Ronimo Games.com','proveedor','Ronimo Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('EA Games','EA Games@mail.com','5518113','5325050','https://www.EA Games.com','proveedor','EA Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Oddworld Inhabitants','Oddworld Inhabitants@mail.com','4923823','5584701','https://www.Oddworld Inhabitants.com','proveedor','Oddworld Inhabitants');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('ORiGO GAMES','ORiGO GAMES@mail.com','2411018','2394060','https://www.ORiGO GAMES.com','proveedor','ORiGO GAMES');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Big Fish Games','Big Fish Games@mail.com','7065645','5190926','https://www.Big Fish Games.com','proveedor','Big Fish Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('BlueGiant Interactive','BlueGiant Interactive@mail.com','5907565','8455470','https://www.BlueGiant Interactive.com','proveedor','BlueGiant Interactive');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Uber Entertainment','Uber Entertainment@mail.com','8452749','4809387','https://www.Uber Entertainment.com','proveedor','Uber Entertainment');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Atomic Games','Atomic Games@mail.com','3230067','2329729','https://www.Atomic Games.com','proveedor','Atomic Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('LoadComplete','LoadComplete@mail.com','8651689','8124214','https://www.LoadComplete.com','proveedor','LoadComplete');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Mindscape','Mindscape@mail.com','9789287','5713731','https://www.Mindscape.com','proveedor','Mindscape');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('ZUXXEZ Entertainment AG','ZUXXEZ Entertainment AG@mail.com','7456052','6791401','https://www.ZUXXEZ Entertainment AG.com','proveedor','ZUXXEZ Entertainment AG');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Valusoft','Valusoft@mail.com','3088929','8530342','https://www.Valusoft.com','proveedor','Valusoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Muse Games','Muse Games@mail.com','3512084','8650440','https://www.Muse Games.com','proveedor','Muse Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Gaijin Games','Gaijin Games@mail.com','6737835','2038507','https://www.Gaijin Games.com','proveedor','Gaijin Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Red Redemption','Red Redemption@mail.com','5115776','9894929','https://www.Red Redemption.com','proveedor','Red Redemption');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Copenhagen Game Productions','Copenhagen Game Productions@mail.com','7917353','9675842','https://www.Copenhagen Game Productions.com','proveedor','Copenhagen Game Productions');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Trion Worlds','Trion Worlds@mail.com','8121790','9248797','https://www.Trion Worlds.com','proveedor','Trion Worlds');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Stout Games','Stout Games@mail.com','3984843','2376993','https://www.Stout Games.com','proveedor','Stout Games');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Nicalis','Nicalis@mail.com','4176075','4965200','https://www.Nicalis.com','proveedor','Nicalis');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Zachtronics Industries','Zachtronics Industries@mail.com','6051868','8600785','https://www.Zachtronics Industries.com','proveedor','Zachtronics Industries');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('beyondthepillars','beyondthepillars@mail.com','9395578','2749103','https://www.beyondthepillars.com','proveedor','beyondthepillars');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('NinjaBee','NinjaBee@mail.com','2550834','2969336','https://www.NinjaBee.com','proveedor','NinjaBee');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Shaven Puppy Ltd','Shaven Puppy Ltd@mail.com','5914115','7322355','https://www.Shaven Puppy Ltd.com','proveedor','Shaven Puppy Ltd');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Facepunch Studios','Facepunch Studios@mail.com','7467779','3609471','https://www.Facepunch Studios.com','proveedor','Facepunch Studios');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Rockstar','Rockstar@mail.com','4054400','2582107','https://www.Rockstar.com','proveedor','Rockstar');

INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('EuroGamer','EuroGamer@mail.com','9214032','8902759','https://www.EuroGamer.com','blog','EuroGamer');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('3djuegos','3djuegos@mail.com','8214559','3326358','https://www.3djuegos.com','blog','3djuegos');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('niubie','niubie@mail.com','6973753','5666061','https://www.niubie.com','blog','niubie');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('nintenderos','nintenderos@mail.com','4713869','1588005','https://www.nintenderos.com','blog','nintenderos');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('akiharablues','akiharablues@mail.com','8081301','3921774','https://www.akiharablues.com','blog','akiharablues');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('vidaextra','vidaextra@mail.com','6015740','3313385','https://www.vidaextra.com','blog','vidaextra');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('pixfans','pixfans@mail.com','3799302','9921249','https://www.pixfans.com','blog','pixfans');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('anaitgames','anaitgames@mail.com','7391700','3713580','https://www.anaitgames.com','blog','anaitgames');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('meristation','meristation@mail.com','3159243','6608242','https://www.meristation.com','blog','meristation');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('deculture','deculture@mail.com','5046293','3988995','https://www.deculture.es','blog','deculture');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('hobbyconsolas','hobbyconsolas@mail.com','3788716','8263585','https://www.hobbyconsolas.com','blog','hobbyconsolas');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('info-gamers','info-gamers@mail.com','6594672','3558873','https://www.info-gamers.com','blog','info-gamers');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('borntoplay','borntoplay@mail.com','2630445','6748093','https://www.borntoplay.es','blog','borntoplay');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gameit','gameit@mail.com','3732143','6848662','https://www.gameit.es','blog','gameit');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('cosasdejuegos','cosasdejuegos@mail.com','2807731','7950553','https://www.cosasdejuegos.es','blog','cosasdejuegos');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('invisiblem','invisiblem@mail.com','5844115','6369753','https://www.invisiblem.net','blog','invisiblem');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('pokemaster','pokemaster@mail.com','8244968','1845042','https://www.pokemaster.es','blog','pokemaster');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('dekazeta','dekazeta@mail.com','3057628','6828184','https://www.dekazeta.net','blog','dekazeta');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('ign','ign@mail.com','5660058','6375099','https://www.ign.com','blog','ign');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('generacionpixel','generacionpixel@mail.com','7026909','3073170','https://www.generacionpixel.com','blog','generacionpixel');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('retrogamer','retrogamer@mail.com','5255989','2348879','https://www.retrogamer.net','blog','retrogamer');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('pocketgamer','pocketgamer@mail.com','3119742','6270705','https://www.pocketgamer.co.uk','blog','pocketgamer');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('pcgamer','pcgamer@mail.com','6317991','5429449','https://www.pcgamer.com','blog','pcgamer');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gametrailers','gametrailers@mail.com','9856193','9328278','https://www.gametrailers.com','blog','gametrailers');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gamasutra','gamasutra@mail.com','2238165','7362434','https://www.gamasutra.com','blog','gamasutra');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('destructoid','destructoid@mail.com','1921105','9257593','https://www.destructoid.com','blog','destructoid');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('neoseeker','neoseeker@mail.com','6753724','5975207','https://www.neoseeker.com','blog','neoseeker');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('joystiq','joystiq@mail.com','7008667','9731611','https://www.joystiq.com','blog','joystiq');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('engadget','engadget@mail.com','7617299','6457193','https://www.engadget.com','blog','engadget');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gamerwithjobs','gamerwithjobs@mail.com','4674054','9026355','https://www.gamerwithjobs.com','blog','gamerwithjobs');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gamefront','gamefront@mail.com','6159797','5438753','https://www.gamefront.com','blog','gamefront');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('thatvideogameblog','thatvideogameblog@mail.com','8060141','7327758','https://www.thatvideogameblog.com','blog','thatvideogameblog');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('ukresistance','ukresistance@mail.com','6591943','7954699','https://www.ukresistance.co.uk','blog','ukresistance');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('tigsource','tigsource@mail.com','8593720','9808381','https://www.tigsource.com','blog','tigsource');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('toucharcade','toucharcade@mail.com','8233593','2178154','https://www.toucharcade.com','blog','toucharcade');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('zehngames','zehngames@mail.com','5093469','7232172','https://www.zehngames.com','blog','zehngames');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gonintendo','gonintendo@mail.com','8118627','6494001','https://www.gonintendo.com','blog','gonintendo');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('kotaku','kotaku@mail.com','8855484','7821564','https://www.kotaku.co.uk','blog','kotaku');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('rockpapershotgun','rockpapershotgun@mail.com','7767559','4429216','https://www.rockpapershotgun.com','blog','rockpapershotgun');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('polygon','polygon@mail.com','8185722','7073385','https://www.polygon.com','blog','polygon');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('shacknews','shacknews@mail.com','5633376','4661451','https://www.shacknews.com','blog','shacknews');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('videoshock','videoshock@mail.com','7763982','7676114','https://www.videoshock.es','blog','videoshock');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('quartertotherre','quartertotherre@mail.com','1718383','8699108','https://www.quartertotherre.com.com','blog','quartertotherre');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('gamespot','gamespot@mail.com','7410743','9957815','https://www.gamespot.com','blog','gamespot');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('vg247','vg247@mail.com','8883666','6035414','https://www.vg247.com','blog','vg247');

INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Prodder','Prodder@mail.com','3574887','4730088','https://www.Prodder.com','proveedor','Prodder');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Voltsillam','Voltsillam@mail.com','8337580','7126846','https://www.Voltsillam.com','proveedor','Voltsillam');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Subin','Subin@mail.com','4840429','9933601','https://www.Subin.com','proveedor','Subin');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Fix San','Fix San@mail.com','5729584','8096489','https://www.Fix San.com','proveedor','Fix San');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Stronghold','Stronghold@mail.com','7769823','2925824','https://www.Stronghold.com','proveedor','Stronghold');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Alpha','Alpha@mail.com','9896334','2550934','https://www.Alpha.com','proveedor','Alpha');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Stringtough','Stringtough@mail.com','8036796','6640064','https://www.Stringtough.com','proveedor','Stringtough');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Ventosanzap','Ventosanzap@mail.com','5404375','3063321','https://www.Ventosanzap.com','proveedor','Ventosanzap');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bitchip','Bitchip@mail.com','4635500','1190027','https://www.Bitchip.com','proveedor','Bitchip');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Keylex','Keylex@mail.com','1055998','8542680','https://www.Keylex.com','proveedor','Keylex');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Holdlamis','Holdlamis@mail.com','6471672','4438998','https://www.Holdlamis.com','proveedor','Holdlamis');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Trippledex','Trippledex@mail.com','2384814','1560619','https://www.Trippledex.com','proveedor','Trippledex');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Andalax','Andalax@mail.com','7640516','3472522','https://www.Andalax.com','proveedor','Andalax');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Toughjoyfax','Toughjoyfax@mail.com','7981143','3825658','https://www.Toughjoyfax.com','proveedor','Toughjoyfax');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Greenlam','Greenlam@mail.com','1991815','7236641','https://www.Greenlam.com','proveedor','Greenlam');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sonair','Sonair@mail.com','8677416','9983919','https://www.Sonair.com','proveedor','Sonair');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Voyatouch','Voyatouch@mail.com','5751910','6110075','https://www.Voyatouch.com','proveedor','Voyatouch');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Cardify','Cardify@mail.com','1082315','1627653','https://www.Cardify.com','proveedor','Cardify');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Temp','Temp@mail.com','3009570','5854061','https://www.Temp.com','proveedor','Temp');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Tempsoft','Tempsoft@mail.com','4867188','8319132','https://www.Tempsoft.com','proveedor','Tempsoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Redhold','Redhold@mail.com','8542562','6301084','https://www.Redhold.com','proveedor','Redhold');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Fixflex','Fixflex@mail.com','1387816','9756119','https://www.Fixflex.com','proveedor','Fixflex');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Domainer','Domainer@mail.com','2301205','6508488','https://www.Domainer.com','proveedor','Domainer');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('It','It@mail.com','8625242','8095314','https://www.It.com','proveedor','It');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sub_Ex','Sub_Ex@mail.com','5143679','7784992','https://www.Sub-Ex.com','proveedor','Sub_Ex');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Fintone','Fintone@mail.com','4831783','6812955','https://www.Fintone.com','proveedor','Fintone');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Latlux','Latlux@mail.com','6330428','4076356','https://www.Latlux.com','proveedor','Latlux');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Namfix','Namfix@mail.com','5891664','3025723','https://www.Namfix.com','proveedor','Namfix');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Home Ing','Home Ing@mail.com','5336377','8323491','https://www.Home Ing.com','proveedor','Home Ing');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Span','Span@mail.com','4838179','6767021','https://www.Span.com','proveedor','Span');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Cardguard','Cardguard@mail.com','7264984','9082987','https://www.Cardguard.com','proveedor','Cardguard');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Zaam_Dox','Zaam_Dox@mail.com','7433830','1645296','https://www.Zaam-Dox.com','proveedor','Zaam_Dox');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bigtax','Bigtax@mail.com','9716223','5333011','https://www.Bigtax.com','proveedor','Bigtax');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Flowdesk','Flowdesk@mail.com','9542393','9857162','https://www.Flowdesk.com','proveedor','Flowdesk');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Konklab','Konklab@mail.com','5823758','7019989','https://www.Konklab.com','proveedor','Konklab');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Job','Job@mail.com','9850680','8269752','https://www.Job.com','proveedor','Job');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Y_find','Y_find@mail.com','6440315','4021819','https://www.Y-find.com','proveedor','Y_find');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Tres_Zap','Tres_Zap@mail.com','1294257','3159024','https://www.Tres-Zap.com','proveedor','Tres_Zap');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Quo Lux','Quo Lux@mail.com','2911145','2519268','https://www.Quo Lux.com','proveedor','Quo Lux');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bitwolf','Bitwolf@mail.com','8846233','5371512','https://www.Bitwolf.com','proveedor','Bitwolf');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Aerified','Aerified@mail.com','6001877','2407733','https://www.Aerified.com','proveedor','Aerified');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Flexidy','Flexidy@mail.com','5574066','2387689','https://www.Flexidy.com','proveedor','Flexidy');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Ronstring','Ronstring@mail.com','3706588','4308342','https://www.Ronstring.com','proveedor','Ronstring');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Gembucket','Gembucket@mail.com','1412176','4536304','https://www.Gembucket.com','proveedor','Gembucket');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Transcof','Transcof@mail.com','2710423','8222522','https://www.Transcof.com','proveedor','Transcof');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Sonsing','Sonsing@mail.com','2042043','8779764','https://www.Sonsing.com','proveedor','Sonsing');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Matsoft','Matsoft@mail.com','9770884','1382591','https://www.Matsoft.com','proveedor','Matsoft');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Daltfresh','Daltfresh@mail.com','9844429','4464561','https://www.Daltfresh.com','proveedor','Daltfresh');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Otcom','Otcom@mail.com','8121938','5662179','https://www.Otcom.com','proveedor','Otcom');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Solarbreeze','Solarbreeze@mail.com','6685584','7500067','https://www.Solarbreeze.com','proveedor','Solarbreeze');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Zathin','Zathin@mail.com','7298519','6077555','https://www.Zathin.com','proveedor','Zathin');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Kanlam','Kanlam@mail.com','8943232','5428830','https://www.Kanlam.com','proveedor','Kanlam');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Duobam','Duobam@mail.com','3033618','3105206','https://www.Duobam.com','proveedor','Duobam');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Tampflex','Tampflex@mail.com','2108763','3556282','https://www.Tampflex.com','proveedor','Tampflex');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Bytecard','Bytecard@mail.com','1637426','1735379','https://www.Bytecard.com','proveedor','Bytecard');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Rank','Rank@mail.com','9289151','1735263','https://www.Rank.com','proveedor','Rank');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Asoka','Asoka@mail.com','8762381','2347046','https://www.Asoka.com','proveedor','Asoka');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Pannier','Pannier@mail.com','3325305','2301159','https://www.Pannier.com','proveedor','Pannier');
INSERT INTO Socios(Nombre,Email,Telefono,Cuenta,Direccion,Tipo,Contraseña) VALUES('Hatity','Hatity@mail.com','1503037','5319150','https://www.Hatity.com','proveedor','Hatity');