insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values (NULL, '21 Susan Trail', 'Brazil', 'Simão Dias', 'Xinlong');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1', NULL, 'Azerbaijan', 'Hacıqabul', 'Babo-Pangulo');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('2', '3 Huxley Alley', NULL, 'Aasiaat', 'Praia');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('3', '4034 Golf View Circle', 'Czech Republic', NULL, 'Villa Ocampo');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('4', '19 Pond Hill', 'Palestinian Territory', 'Khallat Şāliḩ', NULL);
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678906', '414 Marquette Crossing', 'Comoros', 'Dembéni', 'Saba Yoi');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678907', '630 Dexter Way', 'Thailand', 'Khu Khan', 'Nangka');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678908', '73 Havey Crossing', 'Portugal', 'Fenais da Ajuda', 'Calilegua');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678909', '59464 Pond Trail', 'United States', 'Albuquerque', 'Magaozhuang');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678910', '8 Tony Park', 'Norway', 'Bergen', 'Martaban');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678911', '0074 Green Ridge Plaza', 'Russia', 'Almaznyy', 'Ŭiju');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678912', '36279 Spaight Circle', 'Finland', 'Vantaa', 'Butterworth');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678913', '21 Susan Trail', 'Brazil', 'Simão Dias', 'Xinlong');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678914', '993 Vernon Lane', 'Afghanistan', 'Khūgyāṉī', 'Staré Křečany');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678915', '1354 Thackeray Road', 'Portugal', 'Avelinha', 'Barurao');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678916', '0519 Springs Parkway', 'Uzbekistan', 'Beruniy', 'Titao');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678917', '929 Duke Road', 'Ukraine', 'Zakupne', 'Besançon');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678918', '046 Lunder Plaza', 'Indonesia', 'Cibunar', 'Bria');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678919', '96372 Westridge Street', 'Morocco', 'Amouguer', 'Xitiangezhuang');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678920', '7 Meadow Valley Parkway', 'Japan', 'Fujisawa', 'Savannah');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678921', '7 Luster Trail', 'Poland', 'Radzanów', 'Oetuke');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('12345678922', '26912 Crescent Oaks Parkway', 'China', 'Shanghu', 'Kampong Speu');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1001', '636 Dawn Plaza', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Stockholm', 'Jurak Lao’');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1002', '614 John Wall Street', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Montpellier', 'Mamonit');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1003', '24198 Banding Road', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Leigongmiao', 'Pô');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1004', '74080 Sutteridge Alley', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'São Sebastião do Caí', 'Hexi');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1005', '822 1st Road', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Serdobsk', 'Jijia');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1006', '17 Westridge Parkway', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Barueri', 'Örnsköldsvik');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1007', '78039 Forest Run Lane', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Arbois', 'Halle');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1008', '54 Merry Alley', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Ḏânan', 'Verkhnya Rozhanka');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1009', '919 Ramsey Point', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Níkiti', 'Galapa');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1010', '08 7th Trail', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Kedung', 'Nurabelen');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1011', '88760 Elmside Place', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Isiolo', 'Requião');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1012', '84 Blaine Alley', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Cipunglu', 'Orito');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1013', '2028 Bartelt Plaza', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Tulay', 'New Orleans');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1014', '14579 Sycamore Crossing', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Yanwang', 'Esperanza');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1015', '58196 Gulseth Plaza', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Puro', 'Usab');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1016', '501 Hauk Parkway', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Novocheboksarsk', 'Guinabsan');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1017', '82776 Grim Trail', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertabc', 'Zhoukoudian', 'Baratan');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1018', '002 Charing Cross Place', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Phoenix', 'Nanpu');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1019', '4 Mallard Hill', 'qwertyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'El Fahs', 'Nagutskoye');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1020', '06320 Fair Oaks Lane', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Marčelji', 'Põltsamaa');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1021', '24 Prairieview Lane', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Uji', 'Leigao');
insert into DireccionesUsuarios (IdUsuario, Descripcion, Pais, Departamento, Ciudad) values ('1022', '3 Coolidge Avenue', 'abcdtyuiopasdfghjklñzxcvbnmqwertyuiopasdfghjklñzxcvbnmqwertyu', 'Razgrad', 'Pomacanchi');
