insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1001', '8 Jay Junction', 'China', 'Mahekou', 'Týn nad Vltavou');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1002', '1705 Rigney Crossing', 'Canada', 'Roblin', 'Sydney');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1003', '5 4th Street', 'Greece', 'Ouranoupolis', 'As Sawdā');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1004', '5674 Tony Point', 'United States', 'El Paso', 'Duszniki-Zdrój');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1005', '3 Anhalt Way', 'Philippines', 'San Gregorio', 'Isheyevka');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1006', '5 Warner Pass', 'Sweden', 'Arboga', 'Caen');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1007', '4752 Continental Court', 'Japan', 'Tokyo', 'Sanchahe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1008', '37548 Weeping Birch Point', 'Argentina', 'Villa Mercedes', 'Yur’yevets');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1009', '926 Carberry Trail', 'Portugal', 'Ribas', 'Cimonyong');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1010', '9 Ramsey Trail', 'Kazakhstan', 'Aqsay', 'Igreja');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1011', '99 Knutson Alley', 'China', 'Liuqiao', 'Hecun');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1012', '69276 Manley Court', 'Myanmar', 'Thanatpin', 'Mikró Monastíri');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1013', '9005 Troy Hill', 'Indonesia', 'Feondari', 'Masaraway');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1014', '441 Monica Junction', 'Ukraine', 'Molodizhne', 'Ciparay');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1015', '48 Onsgard Point', 'Malaysia', 'Seremban', 'Kināna');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1016', '8 Pierstorff Hill', 'Slovenia', 'Hodoš', 'Kobylin');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1017', '3 Ridgeview Pass', 'China', 'Duobao', 'Gontar');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1018', '21 Bluejay Drive', 'Sweden', 'Klippan', 'Mungwi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1019', '84167 Springs Terrace', 'Sweden', 'Vellinge', 'Gorbatov');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1020', '5233 Twin Pines Avenue', 'France', 'Toulouse', 'Usuki');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1021', '270 Portage Terrace', 'Sweden', 'Stockholm', 'Tauranga');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1022', '98775 Sage Point', 'China', 'Dalongzhan', 'Kirove');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1023', '3 Texas Pass', 'Poland', 'Nielisz', 'Licupis');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1024', '797 Donald Terrace', 'Ukraine', 'Semenivka', 'Charxin');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1025', '057 8th Way', 'Philippines', 'Quezon City', 'Dortmund');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1026', '4185 Schlimgen Hill', 'Peru', 'Huacaschuque', 'Złotniki Kujawskie');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1027', '0 Darwin Alley', 'Indonesia', 'Sumbersih', 'Santa Rosa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1028', '68 Ilene Road', 'Portugal', 'Quintã', 'Valdemarsvik');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1029', '08761 Arizona Plaza', 'Czech Republic', 'Žihle', 'Ciudad Guayana');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1030', '40 Mcbride Pass', 'Philippines', 'Lalagsan', 'General Guido');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1031', '9 Saint Paul Alley', 'Philippines', 'Binabaan', 'San Francisco');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1032', '2 Manitowish Center', 'Colombia', 'Cruces de Anorí', 'Yongping');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1033', '8162 Grover Center', 'Uganda', 'Paidha', 'Lulindi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1034', '1882 2nd Avenue', 'Japan', 'Kuroda', 'Pavlohrad');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1035', '1 Dovetail Street', 'Poland', 'Stryszów', 'Pabean');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1036', '78 West Avenue', 'China', 'Chengfeng', 'Jingling');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1037', '5476 Kenwood Junction', 'South Korea', 'Yeoju', 'Ribeirão Preto');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1038', '225 Vera Alley', 'Indonesia', 'Kliteh', 'Mjamaoué');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1039', '91 Schiller Parkway', 'Nigeria', 'Oke Iho', 'Bantilan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1040', '5597 Derek Road', 'Portugal', 'Fonte do Feto', 'Barra Bonita');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1041', '68545 Lakewood Gardens Road', 'Indonesia', 'Cipinang', 'Aix-en-Provence');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1042', '803 Hoard Drive', 'Brazil', 'Guaranésia', 'Kure');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1043', '0261 Fallview Road', 'Kazakhstan', 'Turkestan', 'Batgrām');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1044', '2 Hoepker Hill', 'Nigeria', 'Obudu', 'Nanzhai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1045', '5 Parkside Alley', 'Syria', 'Ḩarf al Musaytirah', 'Ise');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1046', '230 Parkside Road', 'France', 'Caen', 'Berlin');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1047', '0181 Merry Circle', 'Mongolia', 'Rashaant', 'Sacramento');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1048', '5881 Dixon Crossing', 'Poland', 'Mirosławiec', 'Picton');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1049', '609 5th Circle', 'China', 'Ehen Hudag', 'Palangue');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1050', '27 Browning Place', 'Tanzania', 'Nungwi', 'Vendargues');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1051', '5 Tomscot Trail', 'China', 'Shoushan', 'Roches Noire');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1052', '4 Hansons Pass', 'Indonesia', 'Singkir', 'Vicente Guerrero');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1053', '76 Morning Road', 'China', 'Wenping', 'White River');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1054', '4 Bowman Circle', 'Mexico', 'Santa Clara', 'Shevchenkove');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1055', '16005 East Court', 'Argentina', 'General José de San Martín', 'Tulsa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1056', '13 Washington Junction', 'Indonesia', 'Babakandesa', 'Kawasaki');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1057', '18 Comanche Way', 'China', 'Xiaoyang', 'Zea');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1058', '2410 Magdeline Circle', 'China', 'Dubu', 'Prado Siongco');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1059', '152 Grover Parkway', 'Thailand', 'Nong Ki', 'Lleida');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1060', '8 Morningstar Park', 'Bangladesh', 'Nabīnagar', 'Banos');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1061', '43 Little Fleur Center', 'Czech Republic', 'Město Albrechtice', 'Podhum');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1062', '75676 1st Drive', 'Croatia', 'Rude', 'Nioro du Rip');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1063', '67 Merchant Lane', 'Ukraine', 'Kolodenka', 'Treinta y Tres');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1064', '6 Lake View Trail', 'Indonesia', 'Seoam', 'Malhiao');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1065', '8 Mccormick Circle', 'Czech Republic', 'Modřice', 'Kramators’k');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1066', '52 Village Green Point', 'China', 'Wuyang', 'Weligama');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1067', '8 Hoard Street', 'France', 'Mougins', 'Pivijay');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1068', '0318 Scofield Crossing', 'Thailand', 'Thawi Watthana', 'Pasadena');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1069', '6 Ramsey Trail', 'Poland', 'Jabłoń', 'Ciparasi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1070', '8 Farmco Way', 'China', 'Kuidou', 'Medalem');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1071', '97469 Towne Crossing', 'Brazil', 'Nova Venécia', 'Palebunan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1072', '64 Browning Point', 'South Africa', 'Hopetown', 'Vargas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1073', '63622 3rd Center', 'China', 'Leiwang', 'København');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1074', '8 Old Gate Parkway', 'Nigeria', 'Nsukka', 'Genova');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1075', '26 Talmadge Junction', 'Indonesia', 'Sukorambi', 'Minyat an Naşr');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1076', '8520 Lotheville Road', 'Brazil', 'Aripuanã', 'Guhuai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1077', '14 Farragut Way', 'Israel', 'Mitzpe Ramon', 'Tumba');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1078', '6 Banding Road', 'Kazakhstan', 'Aqtoghay', 'Ostrówek');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1079', '1 Jana Circle', 'Philippines', 'Malibago', 'Ugra');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1080', '2 Commercial Trail', 'Indonesia', 'Baler Baleagung', 'Palalang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1081', '407 Florence Hill', 'Indonesia', 'Ciulu', 'Benoy');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1082', '79 Moose Street', 'Mauritius', 'Mahébourg', 'Guisser');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1083', '5454 Gulseth Place', 'United States', 'Bloomington', 'Babakanlapang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1084', '082 Dayton Trail', 'China', 'Hongdu', 'Mosfilotí');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1085', '36 Morningstar Street', 'China', 'Hedi', 'Mulyadadi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1086', '956 Amoth Court', 'Dominican Republic', 'Concepción de La Vega', 'Dresden');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1087', '3 Anniversary Junction', 'Mexico', 'Emiliano Zapata', 'Naperville');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1088', '05 Sycamore Center', 'Serbia', 'Apatin', 'Shepetivka');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1089', '46 Gerald Alley', 'Honduras', 'El Progreso', 'Cruz das Almas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1090', '2602 Cottonwood Point', 'Indonesia', 'Gandekan', 'Oranmore');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1091', '86 Waubesa Court', 'Albania', 'Pukë', 'Huangcun');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1092', '63552 Gateway Crossing', 'Indonesia', 'Higetegera', 'Dhangarhi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1093', '9775 Hovde Alley', 'Democratic Republic of the Congo', 'Kongolo', 'Shuiyuan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1094', '0587 Buhler Lane', 'Egypt', 'Al Fayyūm', 'Pocsi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1095', '056 Mosinee Street', 'Poland', 'Bledzew', 'Maglajani');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1096', '91 Florence Circle', 'Togo', 'Vogan', 'Keda');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1097', '3 Jackson Park', 'China', 'Chahe', 'Rejoyoso');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1098', '0557 Jay Lane', 'Sweden', 'Ljusdal', 'Guji');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1099', '76 Basil Court', 'Indonesia', 'Jalasenga', 'Suva Reka');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1100', '60032 Crownhardt Street', 'China', 'Longmenfan', 'Haymā’');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1101', '4 Leroy Court', 'Indonesia', 'Krajan', 'Inuvik');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1102', '75 American Ash Road', 'Philippines', 'Paclolo', 'Koungheul');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1103', '220 Union Plaza', 'Greece', 'Khiliomódhi', 'Cihaur');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1104', '444 Golf Point', 'Peru', 'Marco', 'Ourovéni');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1105', '63016 Darwin Road', 'Portugal', 'Feteira Pequena', 'Buriram');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1106', '75 Saint Paul Point', 'Russia', 'Shchëkino', 'Savanna-la-Mar');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1107', '374 Gateway Park', 'Malaysia', 'Kuching', 'San Cristóbal Cucho');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1108', '98 Londonderry Way', 'China', 'Yinjiaxi', 'Esperanza');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1109', '4 Spohn Lane', 'Indonesia', 'Sudimara', 'Kuusjoki');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1110', '5430 Jackson Parkway', 'Poland', 'Łyse', 'Agen');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1111', '57 Prairieview Court', 'Indonesia', 'Cisalak', 'Ningtang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1112', '8627 Randy Court', 'Argentina', 'Capilla del Monte', 'Trongsa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1113', '42 Morningstar Pass', 'Sweden', 'Stockholm', 'Skrunda');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1114', '03013 Warrior Pass', 'China', 'Qingnianlu', 'Daxi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1115', '999 Bayside Parkway', 'Indonesia', 'Airmata', 'Sapouy');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1116', '90 Bartillon Way', 'Poland', 'Lututów', 'Vila Franca do Campo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1117', '03181 Namekagon Lane', 'Japan', 'Shingū', 'Ożarów');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1118', '1 Maple Trail', 'China', 'Yunxiang', 'Baranowo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1119', '35063 Porter Street', 'China', 'Longcheng', 'Makrochóri');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1120', '35 Rockefeller Point', 'China', 'Dunhao', 'Puhja');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1121', '857 Swallow Place', 'Russia', 'Skhodnya', 'Zhuli');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1122', '461 Superior Center', 'Ivory Coast', 'Daloa', 'Heichengzi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1123', '7061 Redwing Place', 'China', 'Wanrongjiang', 'Dondo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1124', '6396 Waywood Point', 'Indonesia', 'Lengkongsari', 'Castries');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1125', '3728 Lakewood Alley', 'Poland', 'Lubichowo', 'Benito Juarez');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1126', '2344 Stuart Crossing', 'China', 'Zibu', 'Sano');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1127', '5017 West Parkway', 'Sweden', 'Kävlinge', 'Pitrufquén');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1128', '9 Quincy Place', 'China', 'Xuexi', 'Poniklá');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1129', '7346 Doe Crossing Court', 'Madagascar', 'Toliara', 'Los Angeles');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1130', '6 Grim Point', 'Honduras', 'San José de Río Tinto', 'Marčelji');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1131', '8455 Montana Street', 'Ukraine', 'Balta', 'Hacıhüseynli');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1132', '5204 Bluejay Hill', 'Czech Republic', 'Dobšice', 'Costa Nova do Prado');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1133', '5 Springview Park', 'France', 'Bourgoin-Jallieu', 'Santa Luċija');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1134', '567 Melody Drive', 'Russia', 'Sergiyev Posad', 'Lixu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1135', '54061 North Terrace', 'Poland', 'Lanckorona', 'Banikoara');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1136', '44015 Arizona Place', 'United States', 'Milwaukee', 'Lebak');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1137', '2 Park Meadow Center', 'Brazil', 'Naviraí', 'Kurchatov');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1138', '2 Sheridan Way', 'China', 'Yuekou', 'Sumuragung');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1139', '73096 Kingsford Hill', 'Maldives', 'Manadhoo', 'Sobral da Abelheira');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1140', '6061 Oak Circle', 'Russia', 'Kunashak', 'Umeå');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1141', '9 Kim Road', 'France', 'Montaigu', 'Antimácheia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1142', '9109 Nova Point', 'Tanzania', 'Itigi', 'Memphis');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1143', '55 Bluestem Way', 'Costa Rica', 'San Vicente de Moravia', 'Itapecerica da Serra');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1144', '99 Annamark Circle', 'Bosnia and Herzegovina', 'Dvorovi', 'Séléa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1145', '81491 Cambridge Park', 'Philippines', 'Nuing', 'Tangdukou');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1146', '6 Anzinger Point', 'Russia', 'Gastello', 'Carabayllo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1147', '1538 Butterfield Pass', 'China', 'Shengshan', 'Itajuípe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1148', '81430 Farragut Place', 'China', 'Danzi', 'Kuncen');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1149', '9 Meadow Valley Street', 'Greece', 'Marmárion', 'Mamuša');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1150', '7 Lukken Junction', 'Japan', 'Chitose', 'Egbe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1151', '5560 Duke Avenue', 'China', 'Sanxi', 'Sumbersih');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1152', '246 Stephen Junction', 'Portugal', 'Vessada', 'Nuku‘alofa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1153', '76147 Petterle Way', 'China', 'Yangdian', 'Ceelbuur');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1154', '6 Talmadge Center', 'Indonesia', 'Ngurensiti', 'Lengshui');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1155', '2 Schiller Parkway', 'Portugal', 'Gaula', 'Baoli');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1156', '258 Vera Hill', 'Colombia', 'Amalfi', 'Erbil');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1157', '558 Anthes Court', 'China', 'Jianlong', 'Barão de São Miguel');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1158', '17 Knutson Trail', 'Morocco', 'Mhamid', 'Kalāleh');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1159', '7 Manufacturers Terrace', 'China', 'Cuozhou', 'Dolní Lhota');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1160', '1 Hooker Trail', 'Slovenia', 'Morje', 'Sutton');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1161', '00 Laurel Drive', 'Sierra Leone', 'Mamboma', 'San Pedro Zacapa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1162', '3 Jay Crossing', 'Cuba', 'Bahía Honda', 'Borås');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1163', '815 Erie Pass', 'China', 'Gurinai', 'Muara Sabak');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1164', '33560 Morningstar Road', 'Sweden', 'Laholm', 'Salgar');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1165', '73 Gateway Trail', 'Argentina', 'Bonpland', 'Cateel');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1166', '96422 Towne Trail', 'Indonesia', 'Satowebrang', 'Porto Calvo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1167', '4514 Blue Bill Park Trail', 'Brazil', 'Tijucas', 'Dayr Sāmit');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1168', '8 Huxley Hill', 'China', 'Longbei', 'San Rafael');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1169', '38561 Loomis Alley', 'Paraguay', 'Yataity del Norte', 'Los Patios');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1170', '3 Merrick Park', 'Ireland', 'Raphoe', 'Kawm Umbū');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1171', '7644 Farmco Way', 'Czech Republic', 'Vroutek', 'Nahiyat Ghammas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1172', '582 Toban Way', 'Russia', 'Muranovo', 'Atimonan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1173', '94594 Wayridge Point', 'Indonesia', 'Sindangsari', 'Toutai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1174', '86534 Superior Crossing', 'Argentina', 'Bahía Blanca', 'Quimper');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1175', '40969 Brickson Park Avenue', 'Iran', 'Garmeh', 'Narutochō-mitsuishi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1176', '327 Tennyson Plaza', 'France', 'Tours', 'Chuncheon');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1177', '23971 Anthes Plaza', 'Indonesia', 'Gading', 'Fenkeng');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1178', '1 Kim Crossing', 'Russia', 'Olenyok', 'Prosperidad');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1179', '47 Fisk Alley', 'Brazil', 'Laranjeiras', '‘Abasān al Kabīrah');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1180', '3 Coolidge Circle', 'China', 'Yulin', 'Didian');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1181', '319 Morning Terrace', 'North Korea', 'Sŏnbong', 'Rulenge');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1182', '17 Burrows Hill', 'Russia', 'Chekmagush', 'Mangdang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1183', '350 Ruskin Alley', 'Philippines', 'Dologon', 'Ventersburg');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1184', '19784 Morrow Lane', 'China', 'Yunlu', 'Monchegorsk');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1185', '6 Holmberg Court', 'Poland', 'Wojsławice', 'Phra Yuen');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1186', '8744 Burning Wood Plaza', 'China', 'Bailianhe', 'Moulins');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1187', '4131 Anthes Street', 'Yemen', 'Al Qurayshīyah', 'Santo Antônio da Platina');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1188', '8613 Sycamore Terrace', 'China', 'Liancheng', 'Giồng Trôm');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1189', '830 Elmside Center', 'Indonesia', 'Cikarang', 'Strážná');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1190', '6508 Express Pass', 'Colombia', 'Corinto', 'Caldas Novas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1191', '190 Express Junction', 'Italy', 'Trieste', 'Klenica');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1192', '7661 Fair Oaks Trail', 'Indonesia', 'Basa', 'Ishimbay');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1193', '5 Roth Plaza', 'Tunisia', 'La Mohammedia', 'Zhong’an');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1194', '454 Schurz Pass', 'France', 'Saint-Priest-en-Jarez', 'Santa Ana');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1195', '96 Mariners Cove Court', 'Spain', 'Telde', 'Houzhai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1196', '9 Morrow Center', 'United States', 'Tyler', 'Auna');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1197', '13467 Bellgrove Center', 'Nigeria', 'Fika', 'Hebu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1198', '5482 Redwing Avenue', 'China', 'Yuwan', 'Rybatskoye');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1199', '521 Aberg Drive', 'Indonesia', 'Pucangkrajan', 'Guadalupe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1200', '07 Bluestem Alley', 'Tanzania', 'Dongobesh', 'Ganquan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1201', '229 Hallows Junction', 'Nigeria', 'Umunede', 'Koumra');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1202', '797 Lukken Court', 'China', 'Chadi', 'Bilian');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1203', '662 Homewood Point', 'Thailand', 'Na Khu', 'Karlskrona');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1204', '614 Lerdahl Trail', 'Russia', 'Staroyur’yevo', 'Örebro');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1205', '27535 Amoth Avenue', 'Zimbabwe', 'Centenary', 'Jiaodai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1206', '97 Crescent Oaks Terrace', 'China', 'Kouzhen', 'Prroshyan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1207', '23 Truax Park', 'Luxembourg', 'Itzig', 'Sam Chuk');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1208', '49 Summer Ridge Lane', 'Philippines', 'Socorro', 'Ampelgading');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1209', '72 Nobel Park', 'Nigeria', 'Fika', 'Yenagoa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1210', '6 Crownhardt Plaza', 'Thailand', 'Chanthaburi', 'Kunyang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1211', '76 Riverside Alley', 'Indonesia', 'Urungpigang', 'Laiguangying');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1212', '5 Springview Avenue', 'Vietnam', 'Thị Trấn Tam Sơn', 'Birmingham');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1213', '4 Maywood Pass', 'Russia', 'Sannikovo', 'Tayu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1214', '3638 Springview Place', 'France', 'Voiron', 'Yucun');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1215', '0 Gulseth Pass', 'Slovenia', 'Dob', 'Porto Formoso');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1216', '76 Bluejay Parkway', 'United States', 'Allentown', 'Góra');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1217', '4 Oxford Drive', 'Indonesia', 'Bagorejo', 'Dallas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1218', '12 Everett Parkway', 'Iraq', '‘Afak', 'Pira');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1219', '4571 Northport Plaza', 'Morocco', 'Sidi Slimane', 'Urasqui');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1220', '71363 Pleasure Lane', 'China', 'Changjiangbu', 'Palmas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1221', '73 Golf Course Center', 'Philippines', 'Pilar', 'Levallois-Perret');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1222', '8 Bunting Lane', 'Vietnam', 'Thị Trấn Yên Ninh', 'Punta del Este');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1223', '2 Buhler Street', 'United States', 'Corpus Christi', 'Dolní Počernice');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1224', '251 Annamark Point', 'France', 'Orléans', 'Bagaces');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1225', '5481 Lakeland Lane', 'Philippines', 'Alae', 'Vođinci');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1226', '1 Stephen Park', 'Portugal', 'Loureiro', 'Mundybash');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1227', '4 Corscot Lane', 'Ukraine', 'Dunaivtsi', 'Ust’-Ilimsk');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1228', '242 Elmside Road', 'Indonesia', 'Kolomanu', 'Tumpukrenteng');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1229', '17383 Northport Place', 'Bangladesh', 'Phultala', 'Kute');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1230', '6542 Straubel Terrace', 'Ukraine', 'Chornyanka', 'Yongfeng');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1231', '67386 Lakewood Gardens Crossing', 'Thailand', 'Khon San', 'Orange');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1232', '625 6th Alley', 'Philippines', 'San Miguel', 'Mama');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1233', '735 Lyons Alley', 'Portugal', 'Corga', 'Vale de Vila');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1234', '3533 Randy Court', 'China', 'Xian’an', 'Géfyra');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1235', '68 Mifflin Parkway', 'Croatia', 'Podhum', 'Jesenice');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1236', '4006 International Crossing', 'Poland', 'Siennica Różana', 'Neuilly-sur-Seine');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1237', '0363 Summit Hill', 'Serbia', 'Nikinci', 'Suḩayl Shibām');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1238', '03 Debra Terrace', 'Peru', 'Puerto Rico', 'Sala');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1239', '612 Union Parkway', 'Poland', 'Ciechanowiec', 'Hobart');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1240', '1 Oriole Trail', 'China', 'Meizhuang', 'La’ershan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1241', '2 Maryland Road', 'Brazil', 'Araraquara', 'Gaxung');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1242', '3 Nobel Center', 'France', 'Altkirch', 'Kariya');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1243', '3 Luster Drive', 'Czech Republic', 'Radnice', 'Berlin');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1244', '877 Marquette Trail', 'Serbia', 'Kulpin', 'Tarikolot');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1245', '89 Cottonwood Alley', 'China', 'Juyuan', 'Sokolnice');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1246', '781 Michigan Avenue', 'Czech Republic', 'Dolní Dvořiště', 'Andapa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1247', '38344 Macpherson Lane', 'Indonesia', 'Samburat', 'Waihai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1248', '498 Merry Circle', 'United States', 'Colorado Springs', 'Qal‘eh Ganj');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1249', '53 Artisan Junction', 'China', 'Yag La', 'Lynn');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1250', '885 Hauk Place', 'Indonesia', 'Cigintung', 'Guanay');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1251', '40 Summerview Terrace', 'China', 'Caojia', 'Chkalov');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1252', '386 Heffernan Junction', 'Indonesia', 'Cipaku', 'Sapiranga');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1253', '5955 North Plaza', 'Poland', 'Kolsko', 'Kukawa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1254', '509 Arkansas Court', 'France', 'Vannes', 'Galátsi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1255', '37311 Pleasure Court', 'Philippines', 'Caronoan West', 'Vilémov');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1256', '31 Laurel Drive', 'Honduras', 'Nombre de Jesús', 'Gandong');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1257', '0121 Lerdahl Hill', 'Poland', 'Siemianowice Śląskie', 'Arapongas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1258', '64 Nevada Way', 'Indonesia', 'Kopang Satu', 'Novi Itebej');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1259', '3 Stoughton Drive', 'Japan', 'Hitoyoshi', 'Tarkastad');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1260', '2720 Pepper Wood Place', 'Russia', 'Admiralteisky', 'Buenavista');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1261', '3 Grayhawk Junction', 'Poland', 'Raszowa', 'Berbek');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1262', '5 Stoughton Road', 'Ukraine', 'Belz', 'Nanping');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1263', '78 Meadow Ridge Hill', 'Poland', 'Brody', 'Kokopo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1264', '2 Bunker Hill Street', 'Mauritius', 'Camp Ithier', 'Kostanay');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1265', '67923 Gateway Street', 'Indonesia', 'Melikkrajan', 'Arendal');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1266', '14 Thierer Place', 'China', 'Dushan', 'Prakhon Chai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1267', '01 Shasta Court', 'Indonesia', 'Cikoneng', 'Aix-en-Provence');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1268', '07 Doe Crossing Street', 'China', 'Xilin', 'Agidel’');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1269', '25515 Fairfield Plaza', 'Armenia', 'T’azagyugh', 'Cibungur');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1270', '18 Hazelcrest Terrace', 'South Sudan', 'Kajok', 'Bulgan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1271', '828 Mccormick Point', 'Indonesia', 'Gunem', 'Kali');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1272', '4108 Eagle Crest Park', 'Brazil', 'Piraí do Sul', 'Xingguo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1273', '08 Crescent Oaks Junction', 'France', 'Ajaccio', 'Villa Hayes');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1274', '088 Schiller Terrace', 'Poland', 'Chwaszczyno', 'Obrera');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1275', '46 Swallow Trail', 'Brazil', 'Paraíso', 'Floreşti');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1276', '9211 5th Lane', 'Indonesia', 'Wonokromo', 'Santo Niño');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1277', '31441 Mccormick Park', 'Georgia', 'Khashuri', 'Gaobu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1278', '67744 Parkside Junction', 'China', 'Kaoshan', 'Ayang-ni');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1279', '9 Upham Parkway', 'Sweden', 'Johanneshov', 'Khadan Khāk');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1280', '343 Swallow Alley', 'Palestinian Territory', 'Bayt Ta‘mar', 'Valsamáta');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1281', '186 Armistice Drive', 'China', 'Cangyou', 'Muonio');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1282', '4546 Fairfield Park', 'Brazil', 'Ipaba', 'Sypniewo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1283', '1 Trailsway Court', 'Germany', 'Dresden', 'Kertapura');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1284', '28163 Upham Center', 'Indonesia', 'Oepula', 'Daja');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1285', '58119 Eastlawn Lane', 'Indonesia', 'Tunasbaru', 'Lloydminster');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1286', '145 Lien Center', 'Canada', 'Woodstock', 'Granja');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1287', '3 Hauk Circle', 'Brazil', 'Bragança Paulista', 'Yambol');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1288', '77044 Myrtle Hill', 'Colombia', 'Guaitarilla', 'Ayabaca');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1289', '56331 Delaware Parkway', 'Philippines', 'Guintubhan', 'Marigot');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1290', '56 Dexter Crossing', 'Tajikistan', 'Konibodom', 'Qaffīn');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1291', '012 Division Street', 'France', 'Saint-Pierre-des-Corps', 'Calomboyan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1292', '33 Dennis Way', 'Philippines', 'Sinacaban', 'Paso de los Libres');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1293', '04709 Charing Cross Park', 'Sweden', 'Norrköping', 'Hongtang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1294', '922 Tony Terrace', 'Ukraine', 'Borodino', 'Stepanivka');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1295', '959 Ohio Pass', 'China', 'Kesha', 'Lian');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1296', '4100 Shopko Alley', 'Syria', 'Tall aḑ Ḑamān', 'Dūāb');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1297', '96 Pierstorff Place', 'Indonesia', 'Pasirhuni', 'Samayac');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1298', '68515 Packers Point', 'Ukraine', 'Shevchenkove', 'Solnice');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1299', '883 Anderson Circle', 'Philippines', 'Lemery', 'Bao’an');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1300', '94799 High Crossing Road', 'Peru', 'Quellouno', 'Dapdap');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1301', '120 Gerald Court', 'Indonesia', 'Ketapang', 'Khomutovo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1302', '33764 Lunder Place', 'Indonesia', 'Wanagiri', 'Shōbu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1303', '15 Acker Place', 'Indonesia', 'Gempolan Wetan', 'Guernica');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1304', '911 Debs Plaza', 'Canada', 'Bonnyville', 'Renhe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1305', '62 Banding Place', 'Comoros', 'Barakani', 'Bella Vista');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1306', '94 Rieder Point', 'Poland', 'Marki', 'Impendle');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1307', '72418 Vera Park', 'Angola', 'Huambo', 'Guxi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1308', '95 Novick Court', 'Vietnam', 'Phù Cát', 'Stryków');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1309', '0 Barby Lane', 'Comoros', 'Moroni', 'Aravissós');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1310', '65981 Myrtle Street', 'Belarus', 'Mar’’ina Horka', 'Xindong');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1311', '222 Old Shore Road', 'Latvia', 'Daugavpils', 'Sete Lagoas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1312', '167 Spaight Point', 'Brazil', 'Santa Rosa de Viterbo', 'Faro');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1313', '41 Springview Place', 'Indonesia', 'Nobo', 'Zibu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1314', '1557 Lotheville Junction', 'Canada', 'Kensington', 'Owczarnia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1315', '898 Montana Lane', 'Thailand', 'Krabi', 'Joaquín Suárez');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1316', '41172 South Hill', 'United States', 'Peoria', 'Zhovti Vody');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1317', '9 Lerdahl Hill', 'Slovenia', 'Lendava', 'Gajrug');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1318', '9 Onsgard Junction', 'Chile', 'Teno', 'Sayang Lauq');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1319', '2537 Gina Avenue', 'China', 'Chengxi', 'Ankou');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1320', '55 1st Place', 'United States', 'Cincinnati', 'Xiangfeng');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1321', '24 Carberry Road', 'China', 'Tangzhai', 'Monze');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1322', '06316 Melvin Way', 'Czech Republic', 'Mladá Boleslav', 'Anjani Barat');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1323', '0 Kim Circle', 'Indonesia', 'Bator', 'Zhoujia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1324', '302 1st Junction', 'China', 'Sunfang', 'Göteborg');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1325', '3 Farragut Park', 'United States', 'Garland', 'Springfield');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1326', '4537 Coleman Parkway', 'China', 'Sanli', 'Rio de Moinhos');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1327', '4861 Garrison Center', 'China', 'Shangshaleng', 'Qinghe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1328', '2 Kingsford Way', 'Equatorial Guinea', 'Ncue', 'Wanfa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1329', '0 Menomonie Way', 'Indonesia', 'Selopuro', 'Yinzhu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1330', '33 Hovde Plaza', 'Germany', 'Hamburg', 'Maofan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1331', '38105 Clyde Gallagher Alley', 'Indonesia', 'Cinunjang', 'Hofors');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1332', '2 Nova Plaza', 'Philippines', 'Balindong', 'San Francisco Zapotitlán');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1333', '95753 Mallory Junction', 'China', 'Wanjiazhuang', 'Rybno');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1334', '0665 Acker Street', 'Ireland', 'Tallaght', 'Dazu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1335', '2937 Rockefeller Place', 'Portugal', 'Malhou', 'Stavanger');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1336', '8 Fairview Center', 'Iceland', 'Vestmannaeyjar', 'Agassiz');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1337', '6959 Utah Drive', 'Venezuela', 'Guanta', 'Dalianwan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1338', '6 Northwestern Avenue', 'Bolivia', 'Santa Cruz de la Sierra', 'Moss');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1339', '81270 Kedzie Park', 'Colombia', 'Paicol', 'Raszczyce');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1340', '8140 South Alley', 'Gambia', 'Sutukoba', 'Taungoo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1341', '1 Express Alley', 'Ecuador', 'Loja', 'Castelo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1342', '03 Brickson Park Parkway', 'Argentina', 'San Fernando del Valle de Catamarca', 'Orlando');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1343', '9076 Bay Junction', 'Mongolia', 'Jargalant', 'Pasirreungit');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1344', '8050 Morning Trail', 'China', 'Oumiao', 'Belung Satu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1345', '9688 Union Terrace', 'Portugal', 'Meirinhas', 'Buawan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1346', '5 Orin Junction', 'Russia', 'Sergokala', 'Qianzhou');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1347', '6 Portage Parkway', 'Argentina', 'General Enrique Godoy', 'Wola Rębkowska');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1348', '28207 Sutteridge Court', 'Brazil', 'Maceió', 'Chaodi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1349', '41371 Sundown Pass', 'Poland', 'Korczew', 'Mellieħa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1350', '16744 Lotheville Pass', 'Portugal', 'Sanguinheira', 'Loakulu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1351', '24488 Anhalt Terrace', 'Thailand', 'Kranuan', 'Ar Rujum');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1352', '29917 Sloan Terrace', 'Mauritius', 'Calebasses', 'Emar');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1353', '6339 Veith Hill', 'France', 'Nevers', 'Dąbie');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1354', '93 3rd Street', 'Russia', 'Khasavyurt', 'Nanxia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1355', '57453 La Follette Hill', 'Greece', 'Kýthnos', 'Mananjary');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1356', '917 Stuart Circle', 'Philippines', 'Malasiqui', 'Virojoki');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1357', '31 Rusk Park', 'Ireland', 'Clondalkin', 'New York City');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1358', '1577 Swallow Lane', 'Portugal', 'São Mamede de Infesta', 'Calimete');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1359', '285 Ronald Regan Drive', 'Indonesia', 'Purbalingga', 'Ampahana');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1360', '46358 Kim Center', 'Guatemala', 'San Agustín Acasaguastlán', 'Casigua El Cubo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1361', '93293 Elmside Pass', 'Philippines', 'Mababanaba', 'Arrah');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1362', '55370 Lindbergh Court', 'France', 'Nice', 'Ezeiza');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1363', '6965 Rutledge Crossing', 'Nigeria', 'Lafiagi', 'Ţawr al Bāḩah');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1364', '1 Express Road', 'China', 'Saga', 'Udi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1365', '86943 Dahle Junction', 'Philippines', 'San Rafael', 'Marseille');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1366', '74 Northport Way', 'China', 'Luobuqiongzi', 'Kujung');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1367', '3750 Carey Terrace', 'Indonesia', 'Klagen', 'Zielona Góra');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1368', '5 Harbort Trail', 'Barbados', 'Bridgetown', 'Pirassununga');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1369', '474 Hooker Crossing', 'China', 'Yanghou', 'Seattle');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1370', '0 Hermina Road', 'Greece', 'Velestíno', 'Büzmeýin');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1371', '3066 Moland Road', 'China', 'Chikeng', 'Kájov');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1372', '1 Fairfield Avenue', 'Brazil', 'Coronel Vivida', 'Apodi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1373', '15 Maple Wood Trail', 'Russia', 'Kabardinka', 'Kuala Lumpur');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1374', '4014 Ryan Road', 'Zimbabwe', 'Kadoma', 'Tarauacá');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1375', '91719 Merrick Alley', 'Malaysia', 'Kota Kinabalu', 'Pleiku');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1376', '844 Grayhawk Avenue', 'Indonesia', 'Jatiklampok', 'Petani');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1377', '89 Union Crossing', 'China', 'Huangtian', 'Daming');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1378', '9922 Russell Trail', 'China', 'Rongcheng', 'Naas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1379', '10876 Judy Crossing', 'Portugal', 'Leitões', 'Luleå');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1380', '70025 Talisman Road', 'China', 'Tuzhai', 'Litian');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1381', '28517 Namekagon Pass', 'China', 'Baiyun', 'Eixo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1382', '05 Vernon Junction', 'Indonesia', 'Palue', 'Petaẖ Tiqwa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1383', '40 Victoria Plaza', 'Brazil', 'Delmiro Gouveia', 'Fengle');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1384', '0240 Schlimgen Street', 'Colombia', 'Itagüí', 'Hongqi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1385', '626 Dennis Street', 'Gambia', 'Karantaba', 'Sanjiang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1386', '966 Cascade Court', 'Indonesia', 'Sumurwaru', 'Rimouski');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1387', '01097 Ridgeway Hill', 'Russia', 'Rognedino', 'Jinniu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1388', '1 Montana Trail', 'China', 'Jilong', 'Kiukasen');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1389', '720 Anniversary Hill', 'Russia', 'Kiyevskoye', 'Stupsk');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1390', '7086 Lakewood Gardens Lane', 'Netherlands', 'Lelystad', 'Nijmegen');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1391', '2910 Fieldstone Avenue', 'Indonesia', 'Boncis', 'Telêmaco Borba');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1392', '85347 Chinook Parkway', 'Lithuania', 'Nida', 'Zhongyuan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1393', '33581 Brentwood Hill', 'Sweden', 'Vänersborg', 'Miguel Hidalgo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1394', '1 Novick Court', 'Russia', 'Ullubiyaul', 'Tamberías');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1395', '48 Bartillon Drive', 'Yemen', 'Bayt ‘Adhāqah', 'Megion');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1396', '6391 Becker Way', 'China', 'Shangma', 'Myanaung');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1397', '937 Rockefeller Crossing', 'Belize', 'Belize City', 'Santa Rosa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1398', '647 Stephen Circle', 'Indonesia', 'Banjarmasin', 'Turośń Kościelna');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1399', '0678 Truax Terrace', 'Ukraine', 'Kuznetsovs’k', 'Arma');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1400', '68516 Moose Court', 'China', 'Zhengji', 'Thanatpin');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1401', '4404 Farragut Road', 'Vietnam', 'Thị Trấn Quán Lào', 'Staryy Krym');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1402', '35935 Roth Place', 'Russia', 'Uvarovo', 'Lampitak');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1403', '1656 Michigan Junction', 'Russia', 'Pashkovskiy', 'Port Hawkesbury');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1404', '16 Almo Alley', 'Russia', 'Biskamzha', 'Waru');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1405', '9 Lindbergh Court', 'Czech Republic', 'Lázně Kynžvart', 'Sutton');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1406', '8 Johnson Road', 'China', 'Huangzhai', 'Cinyawang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1407', '68748 Red Cloud Way', 'Sweden', 'Köping', 'Carpalho');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1408', '29 Dovetail Place', 'Greece', 'Filothéi', 'Khawr Maksar');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1409', '6 Fairview Junction', 'Kazakhstan', 'Zhosaly', 'Putinci');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1410', '7 Graedel Hill', 'Indonesia', 'Halimaung Jaya (F-3)', 'Xingang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1411', '3321 Swallow Point', 'Japan', 'Owase', 'Santol');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1412', '0773 Scofield Alley', 'Serbia', 'Putinci', 'Lamak');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1413', '75280 Glacier Hill Drive', 'Brazil', 'Acaraú', 'Myasnikyan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1414', '0 Annamark Plaza', 'Canada', 'Burgeo', 'Lazaro Cardenas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1415', '62 Packers Park', 'Ukraine', 'Kotel’va', 'Bagong Pagasa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1416', '1800 Ruskin Drive', 'Ukraine', 'Chynadiyovo', 'Travesía');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1417', '3680 Heath Court', 'Philippines', 'Santo Tomas', 'Tønsberg');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1418', '78 Gerald Crossing', 'China', 'Dagu', 'Petaling Jaya');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1419', '50780 Grasskamp Alley', 'Madagascar', 'Belo sur Tsiribihina', 'Bodzentyn');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1420', '2192 Crowley Drive', 'Nigeria', 'Kafarati', 'Thanh Ba');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1421', '98 Lakewood Gardens Center', 'Russia', 'Kurovskoye', 'Biwer');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1422', '88794 Oxford Pass', 'Russia', 'Komsomolets', 'Krojo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1423', '953 Bowman Circle', 'Albania', 'Guri i Zi', 'Qiaobian');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1424', '2 Londonderry Drive', 'Peru', 'Pacasmayo', 'Tost');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1425', '41901 Washington Circle', 'Belarus', 'Parychy', 'Zunilito');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1426', '35068 Straubel Hill', 'Malawi', 'Blantyre', 'Rakiv Lis');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1427', '5549 Kropf Way', 'Mauritius', 'Quatre Bornes', 'Arivonimamo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1428', '71 Larry Pass', 'Poland', 'Rzepiennik Strzyżewski', 'Datang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1429', '21537 Pleasure Avenue', 'United States', 'Toledo', 'Gwangjeok');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1430', '3 Shoshone Place', 'Philippines', 'Consolacion', 'Noebesa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1431', '84 Eastwood Center', 'Indonesia', 'Orong', 'Vadstena');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1432', '38609 Rieder Trail', 'Philippines', 'Mendez-Nuñez', 'Pérez');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1433', '0 Rieder Center', 'Portugal', 'Canhestros', 'Lukrejo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1434', '83 Sullivan Terrace', 'Japan', 'Masuda', 'Guaxupé');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1435', '9121 Golden Leaf Alley', 'Philippines', 'Gubat', 'Zhujiang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1436', '9 Grayhawk Street', 'Russia', 'Nizhnyaya Tavda', 'Mērsrags');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1437', '4594 Mariners Cove Avenue', 'China', 'Yuquan', 'Włosienica');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1438', '2 Bellgrove Drive', 'Russia', 'Lesogorsk', 'Ping’an');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1439', '19 David Parkway', 'Indonesia', 'Pogag', 'Zhendu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1440', '564 Maple Circle', 'Thailand', 'Kamphaeng Phet', 'Ningdun');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1441', '4 Gerald Drive', 'Botswana', 'Gaborone', 'Thymianá');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1442', '76 Maple Wood Avenue', 'Argentina', 'Alejandro Roca', 'Cabaiguán');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1443', '2093 Melby Court', 'Thailand', 'Hua Sai', 'Asenovgrad');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1444', '79537 Golf Lane', 'Russia', 'Bayangol', 'Welibo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1445', '9331 Hintze Alley', 'Russia', 'Sergeyevka', 'Paiçandu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1446', '290 Golf Course Point', 'Belarus', 'Lahishyn', 'Sincelejo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1447', '45724 4th Road', 'Moldova', 'Floreşti', 'Terawas');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1448', '799 Schmedeman Alley', 'China', 'Nagqu', 'Bāgh-e Maīdān');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1449', '8525 Kinsman Court', 'Colombia', 'Murindó', 'Fada N''gourma');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1450', '670 Maple Terrace', 'China', 'Shadui', 'Holma');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1451', '05201 Bartillon Place', 'Tanzania', 'Namikupa', 'Lisewo');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1452', '6617 Evergreen Parkway', 'Norway', 'Oslo', 'Liulihe');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1453', '86069 Rowland Hill', 'Russia', 'Sapernoye', 'Erdu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1454', '83588 Anniversary Way', 'Philippines', 'Sogod', 'Kiffa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1455', '781 Towne Crossing', 'United States', 'El Paso', 'Dnipryany');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1456', '82621 Mandrake Hill', 'Sierra Leone', 'Mobai', 'Otrokovice');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1457', '5 Lawn Court', 'Denmark', 'Frederiksberg', 'Tuamese');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1458', '701 Rieder Drive', 'China', 'Baishui', 'Segovia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1459', '74 Kenwood Crossing', 'Peru', 'Mache', 'Salvacion');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1460', '25401 West Park', 'Indonesia', 'Pilang', 'Yuanda');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1461', '20 Barnett Park', 'Philippines', 'Bolaoit', 'Hanjia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1462', '57 Lunder Pass', 'Indonesia', 'Sugihmukti', 'Rezh');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1463', '6926 Nevada Park', 'Brazil', 'Niquelândia', 'Yangirabot');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1464', '73457 Goodland Terrace', 'China', 'Moganshan', 'Sam Ngam');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1465', '29847 Caliangt Drive', 'Russia', 'Novoshakhtinskiy', 'Oemofa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1466', '895 2nd Drive', 'Brazil', 'Costeira do Pirajubae', 'Batutulis');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1467', '656 Dakota Plaza', 'China', 'Xiyang', 'Shuangmiao');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1468', '57831 Goodland Junction', 'China', 'Taiping', 'Fengxizhai');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1469', '57 Waywood Place', 'China', 'Yinping', 'Yong’an');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1470', '98 Roth Plaza', 'Peru', 'Cabanaconde', 'Simões Filho');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1471', '1733 Onsgard Court', 'Indonesia', 'Jawatiwa', 'Jamshoro');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1472', '3118 Acker Trail', 'Honduras', 'Agalteca', 'Lodwar');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1473', '4 Lake View Terrace', 'Poland', 'Stęszew', 'Xinminxiang');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1474', '4 Division Road', 'France', 'Toulouse', 'Noveleta');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1475', '2031 Bluejay Place', 'Bolivia', 'Roboré', 'Dancheng');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1476', '29282 Reindahl Way', 'Sweden', 'Örebro', 'Cañete');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1477', '66614 Old Gate Crossing', 'Morocco', 'Kenitra', 'Staraya Stanitsa');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1478', '5969 Montana Hill', 'France', 'Alfortville', 'Nishinoomote');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1479', '52260 Bartillon Center', 'France', 'Lyon', 'San Carlos');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1480', '646 Crest Line Avenue', 'Indonesia', 'Kauman', 'Asia');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1481', '9 Grayhawk Crossing', 'Indonesia', 'Sindanghayu', 'Greensboro');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1482', '42531 Prairie Rose Parkway', 'Norway', 'Moss', 'Kuanfatu');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1483', '1471 Gateway Court', 'China', 'Dadianzi', 'Hongshanzui');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1484', '56 Hanover Parkway', 'France', 'Périgueux', 'Mandala');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1485', '79 Declaration Alley', 'Chile', 'Chiguayante', 'Yotsukaidō');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1486', '703 Kings Court', 'Greece', 'Arkhaía Kórinthos', 'Qarqania');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1487', '69 Anzinger Drive', 'China', 'Rizhao', 'Phayao');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1488', '0242 Delladonna Junction', 'Peru', 'Sinchao', 'Małkinia Górna');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1489', '1 Spenser Court', 'China', 'Suocheng', 'Qiqian');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1490', '08 3rd Terrace', 'Indonesia', 'Soko', 'Bukor');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1491', '5455 Holmberg Circle', 'Poland', 'Sosnówka', 'Herrera');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1492', '7570 Carioca Terrace', 'Philippines', 'Concepcion', 'Tuchengzi');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1493', '3214 Di Loreto Trail', 'Montserrat', 'Brades', 'Tairan Camp');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1494', '800 Knutson Drive', 'Peru', 'Huaylillas', 'Alilem');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1495', '32044 Thompson Trail', 'Indonesia', 'Haruman', 'Marco');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1496', '5 Melby Circle', 'Norway', 'Bodø', 'Foča');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1497', '561 Tomscot Way', 'Nigeria', 'Ohafia-Ifigh', 'Irahuan');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1498', '04809 American Street', 'Serbia', 'Savski Venac', 'Evansville');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1499', '4736 Holmberg Court', 'Croatia', 'Vuka', 'Aygeshat');
insert into DireccionesEstablecimientos (IdEstablecimiento, Descripcion, Pais, Departamento, Ciudad) values ('1500', '32626 Schiller Place', 'Hong Kong', 'Tuen Mun', 'Tengah');
