/*Actores*/
CREATE OR REPLACE PACKAGE PA_USUARIO IS
    PROCEDURE AD_DIRECCION_U(xUsername IN VARCHAR, xPais IN VARCHAR, xCiudad IN VARCHAR, xDepartamento IN VARCHAR, xDescripcion IN VARCHAR);
    PROCEDURE MO_DIRECCION(xUsername IN VARCHAR, xPais IN VARCHAR DEFAULT NULL, xCiudad IN VARCHAR DEFAULT NULL, xDepartamento IN VARCHAR DEFAULT NULL, xDescripcion IN VARCHAR DEFAULT NULL);
    PROCEDURE DEL_DIRECCION_U(xIDDireccion IN VARCHAR);
    PROCEDURE AD_USUARIO(xUsername IN VARCHAR, XContraseña IN VARCHAR, xEmail IN VARCHAR);
    PROCEDURE MO_USUARIO(xUsername IN VARCHAR, xContraseña IN VARCHAR);
    PROCEDURE DEL_USUARIO(xUsername IN VARCHAR);
    FUNCTION CO_Direccion(xIDDireccion IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Direcciones_U(xUsername IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Reviews(xNombre IN VARCHAR ,xPlataforma IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_ProductProx RETURN SYS_REFCURSOR;
    FUNCTION CO_Productos(xNombre IN VARCHAR , xPlataforma IN VARCHAR, xFormato IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Producto(xIDDetalle IN VARCHAR, xUsername IN VARCHAR) RETURN SYS_REFCURSOR;
    PROCEDURE MakeAClick(xIDDetalle IN VARCHAR, xUsername IN VARCHAR, xOut OUT SYS_REFCURSOR);
    PROCEDURE MakeAClick(xIDReview IN VARCHAR, xUsername IN VARCHAR, xOut OUT SYS_REFCURSOR);
    FUNCTION CO_Direcciones(xUsername IN VARCHAR) RETURN SYS_REFCURSOR;
END PA_USUARIO;
/
CREATE OR REPLACE PACKAGE PA_Blogger IS
    PROCEDURE AD_USUARIO(xNombre IN VARCHAR, xEmail IN VARCHAR, xTelefono IN VARCHAR, xCuenta IN VARCHAR, xDireccion IN VARCHAR, xTipo IN VARCHAR, xContraseña IN VARCHAR);
    PROCEDURE MO_USUARIO(xIDSocio IN VARCHAR, xEmail IN VARCHAR DEFAULT NULL, xTelefono IN VARCHAR DEFAULT NULL, xCuenta IN VARCHAR DEFAULT NULL, xDireccion IN VARCHAR DEFAULT NULL, xContraseña IN VARCHAR DEFAULT NULL);
    PROCEDURE DEL_USUARIO(xIDSocio IN VARCHAR);
    FUNCTION CO_Reviews(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_AVGReview(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_BestReview(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_SPagos(xIDSocio IN VARCHAR) RETURN SYS_REFCURSOR;
END PA_Blogger;
/
CREATE OR REPLACE PACKAGE PA_Proveedor IS
    PROCEDURE AD_USUARIO(xNombre IN VARCHAR, xEmail IN VARCHAR, xTelefono IN VARCHAR, xCuenta IN VARCHAR, xDireccion IN VARCHAR, xTipo IN VARCHAR, xContraseña IN VARCHAR);
    PROCEDURE MO_USUARIO(xIDSocio IN VARCHAR, xEmail IN VARCHAR DEFAULT NULL, xTelefono IN VARCHAR DEFAULT NULL, xCuenta IN VARCHAR DEFAULT NULL, xDireccion IN VARCHAR DEFAULT NULL, xContraseña IN VARCHAR DEFAULT NULL);
    PROCEDURE DEL_USUARIO(xIDSocio IN VARCHAR);
    PROCEDURE AD_DIRECCION_S(xIDEstablecimiento IN VARCHAR, xPais IN VARCHAR, xCiudad IN VARCHAR, xDepartamento IN VARCHAR, xDescripcion IN VARCHAR);
    PROCEDURE DEL_DIRECCION_S(xIDDireccion IN VARCHAR);
    FUNCTION CO_Direccion(xIDDireccion IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Direcciones(xIDEstablecimiento IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_PCobros(xIDProveedor IN VARCHAR) RETURN SYS_REFCURSOR;
END PA_Proveedor;
/
CREATE OR REPLACE PACKAGE PA_Admin IS
    PROCEDURE AD_Auspiciado(xIDDetalle IN VARCHAR);
    PROCEDURE DEL_Auspiciado(xIDAuspiciado IN VARCHAR);
    PROCEDURE AD_Genero(xNombre IN VARCHAR);
    PROCEDURE DEL_Genero(xNombre IN VARCHAR);
    FUNCTION CO_Ganancias(Fecha1 IN VARCHAR, Fecha2 IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Auspiciados RETURN SYS_REFCURSOR;
    FUNCTION CO_ProductProx RETURN SYS_REFCURSOR;
    FUNCTION CO_PCobros(xIDProveedor IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_SPagos(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
END PA_Admin;