/*CRUDS*/
CREATE OR REPLACE PACKAGE PC_PRODUCTOS IS
    PROCEDURE AD_PRODUCTO(xNombre IN VARCHAR, xPrecioBase IN NUMBER, xPrecioActual IN NUMBER, xFLanzamiento IN DATE, xValoracion IN NUMBER, xPlataforma IN VARCHAR, xEspecificacion IN VARCHAR, xIDProveedor IN VARCHAR, xDesarrolladora IN VARCHAR, xFormato IN VARCHAR, xTipo IN VARCHAR, xLink IN VARCHAR);
    PROCEDURE MO_PRODUCTO(xIDProducto IN VARCHAR, xPrecioBase IN INTEGER DEFAULT NULL, xPrecioActual IN INTEGER DEFAULT NULL, xFLanzamiento IN DATE DEFAULT NULL, xValoracion IN NUMBER DEFAULT NULL);
    PROCEDURE DEL_PRODUCTO(xIDProducto IN VARCHAR);
    FUNCTION CO_ProductProx RETURN SYS_REFCURSOR;
    FUNCTION CO_Productos(xNombre IN VARCHAR , xPlataforma IN VARCHAR, xFormato IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Producto(xIDDetalle IN VARCHAR, xUsername IN VARCHAR) RETURN SYS_REFCURSOR;
    PROCEDURE MakeAClick(xIDDetalle IN VARCHAR, xUsername IN VARCHAR, xOut OUT SYS_REFCURSOR);
END PC_PRODUCTOS;
/
CREATE OR REPLACE PACKAGE PC_COBROS IS
    PROCEDURE AD_COBRO(xIDProveedor IN VARCHAR, xIDLink IN VARCHAR);
    FUNCTION CO_PCobros(xIDProveedor IN VARCHAR) RETURN SYS_REFCURSOR; 
END PC_COBROS;
/
CREATE OR REPLACE PACKAGE PC_PAGOS IS
    PROCEDURE AD_PAGO(xIDBlog IN VARCHAR,xIDLink IN VARCHAR);
    FUNCTION CO_SPagos(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR; 
END PC_PAGOS;
/
CREATE OR REPLACE PACKAGE PC_USUARIOS IS
    PROCEDURE AD_USUARIO(xUsername IN VARCHAR, XContraseña IN VARCHAR, xEmail IN VARCHAR);
    PROCEDURE MO_USUARIO(xUsername IN VARCHAR, xContraseña IN VARCHAR);
    PROCEDURE DEL_USUARIO(xUsername IN VARCHAR);
END PC_USUARIOS;
/
CREATE OR REPLACE PACKAGE PC_DIRECCIONES IS 
    PROCEDURE AD_DIRECCION_U(xUsername IN VARCHAR, xPais IN VARCHAR, xCiudad IN VARCHAR, xDepartamento IN VARCHAR, xDescripcion IN VARCHAR);
    PROCEDURE AD_DIRECCION_S(xIDEstablecimiento IN VARCHAR, xPais IN VARCHAR, xCiudad IN VARCHAR, xDepartamento IN VARCHAR, xDescripcion IN VARCHAR);
    PROCEDURE MO_DIRECCION(xUsername IN VARCHAR, xPais IN VARCHAR DEFAULT NULL, xCiudad IN VARCHAR DEFAULT NULL, xDepartamento IN VARCHAR DEFAULT NULL, xDescripcion IN VARCHAR DEFAULT NULL);
    PROCEDURE DEL_DIRECCION_U(xIDDireccion IN VARCHAR);
    PROCEDURE DEL_DIRECCION_S(xIDDireccion IN VARCHAR);
    FUNCTION CO_Direccion_U(xIDDireccion IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Direcciones_U(xUsername IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Direccion_S(xIDDireccion IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Direcciones_S(xIDEstablecimiento IN VARCHAR) RETURN SYS_REFCURSOR;
END PC_DIRECCIONES;
/
CREATE OR REPLACE PACKAGE PC_REVIEWS IS
    PROCEDURE AD_Review(xNombre IN VARCHAR, xProducto IN VARCHAR, xPlataforma IN VARCHAR, xPertenencia IN VARCHAR, xFPublicacion IN DATE, xValoracion IN NUMBER, xRedireccionamiento IN VARCHAR);
    PROCEDURE MO_Review(xIDReview IN VARCHAR, xValoracion IN NUMBER);
    PROCEDURE DEL_Review(xIDReview IN VARCHAR);
    FUNCTION CO_Reviews_U(xNombre IN VARCHAR, xPlataforma IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_Reviews_S(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_AVGReview(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
    FUNCTION CO_BestReview(xIDBlog IN VARCHAR) RETURN SYS_REFCURSOR;
    PROCEDURE MakeAClick(xIDReview IN VARCHAR, xUsername IN VARCHAR, xOut OUT SYS_REFCURSOR);
END PC_REVIEWS;
/
CREATE OR REPLACE PACKAGE PC_SOCIOS IS
    PROCEDURE AD_USUARIO(xNombre IN VARCHAR, xEmail IN VARCHAR, xTelefono IN VARCHAR, xCuenta IN VARCHAR, xDireccion IN VARCHAR, xTipo IN VARCHAR, xContraseña IN VARCHAR, xModalidad IN VARCHAR DEFAULT NULL);
    PROCEDURE MO_USUARIO(xIDSocio IN VARCHAR, xEmail IN VARCHAR DEFAULT NULL, xTelefono IN VARCHAR DEFAULT NULL, xCuenta IN VARCHAR DEFAULT NULL, xDireccion IN VARCHAR DEFAULT NULL, xContraseña IN VARCHAR DEFAULT NULL);
    PROCEDURE DEL_USUARIO(xIDSocio IN VARCHAR);
END PC_SOCIOS;
/
